### ISSUE TITLE
[1.12-7.0.28.814] Server Crash on Startup

### ISSUE THREAD

**Issue by Kris1432** [progwml6/ironchest#103]
By adding 1 mod at a time, I have figured out that Iron Chests is causing a crash on dedicated server startup

Forge: 2373
Cause: Startup Crash

Crashlog: https://pastebin.com/2kh03RHi

**Comment by Placid-Storm** [comment]
I can second this. I got the exact same crash and removing Iron Chest fixed it. I was using Forge:2370.
