### ISSUE TITLE
Chest/Shulker upgrades overlapping recipes

### ISSUE THREAD

**Issue by GuntherDW** [progwml6/ironchest#106]
In the 1.12 version of IronChests there are overlapping recipes causing you to, when you were meant to craft the chest upgrades you get the shulker ones instead.

http://i.imgur.com/0UlXfD5.png
The item in the middle of the second recipe is TechReborn's "Refined Iron", but it cycles to regular iron as well.
The same issue is happening for the other upgrades that take the same route as regular chests.
- Iron to Gold
- Gold to Diamond
- Copper to Silver
- Silver to Gold
- Copper to Iron
- Diamond to Crystal
- Diamond to Obsidian

Versions:
 - Minecraft: 1.12
 - Forge: 14.21.1.2443
 - IronChests: 7.0.31.818

**Comment by davqvist** [comment]
Having the same issue but vice versa, being not able to craft Shulker Upgrades.

**Comment by JennyLeeP** [comment]
Can confirm , recipes are conflicting. Cannot craft Shulker box upgrades.

**Comment by tornewuff** [comment]
Yup, the recipes are just identical in the json definitions in the source code - nothing weird going on :)

Will have to change the recipe with crafttweaker for now...

**Comment by alexbegt** [comment]
I have fixed these conflicting recipes once and for all.
