### ISSUE TITLE
[1.12.2] Unkonwn Colour Change

### ISSUE THREAD

**Issue by Draskh** [progwml6/ironchest#114]
The colour of one of my chests changed for no reason. Sometimes it changes back. 
![2017-12-08_19 29 54](https://user-images.githubusercontent.com/26455012/33804292-2c5b3534-dda2-11e7-8712-681886dcb69e.png)

**Comment by alexbegt** [comment]
I was never able to reproduce this issue. If it still occurs please reopen a new ticket. Thanks!

**Comment by Draskh** [comment]
Does not occur anymore I think.
