### ISSUE TITLE
1.12.2 Inventory Tweaks

### ISSUE THREAD

**Issue by ghost** [progwml6/ironchest#116]
On the GUI for Crystal, Obsidian and Diamond chests the inventory tweaks sorting tabs dont show properly, the middle 2 buttons are missing.

from the inventory tweaks issues page it seems to suggest that mods need to use the InventoryTweaks API to position the buttons

https://github.com/Inventory-Tweaks/inventory-tweaks/issues/502
https://github.com/Inventory-Tweaks/inventory-tweaks/issues/474

is this something you can fix? or should I report it to InventoryTweaks?

**Comment by alexbegt** [comment]
This is because InvTweaks does not add the second and third button to the inventory when the inventory has over 9 rows, The Diamond, Crystal and Obsidian all have 12 rows in total. I am unable to fix this on IronChest's end
