### ISSUE TITLE
Can't craft higher than iron shulker box

### ISSUE THREAD

**Issue by LockManipulator** [progwml6/ironchest#117]
Using the iron to gold upgrade on it just opens the box.

**Comment by alexbegt** [comment]
Are you holding shift while trying to upgrade it?

**Comment by LockManipulator** [comment]
I feel dumb. Thank for the tip!

**Comment by LockManipulator** [comment]
Actually, just tried it. Still doesn't work. I think it's because I can't
craft the upgrade for shulker boxes. Only for normal chests. The recipe seems to be the same for both of them.

**Comment by alexbegt** [comment]
I have fixed the conflicting recipes.
