### ISSUE TITLE
iron chest crashes game

### ISSUE THREAD

**Issue by sundropman95** [progwml6/ironchest#137]
im being told by minecraft that the version is invalid.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  FMLPlugin (elulib-0.1.12.jar)
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/28/18 6:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Iron Chest (ironchest)
Caused by: java.lang.ExceptionInInitializerError
	at cpw.mods.ironchest.client.ClientProxy.preInit(ClientProxy.java:39)
	at cpw.mods.ironchest.IronChest.preInit(IronChest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:637)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at io.github.strikerrocker.vt.capabilities.SelfPlantingProvider.<init>(SelfPlantingProvider.java:12)
	at io.github.strikerrocker.vt.events.VTEventHandler.addItemCaps(VTEventHandler.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_187_VTEventHandler_addItemCaps_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:657)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:627)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
	at cpw.mods.ironchest.client.renderer.chest.TileEntityIronChestRenderer.<clinit>(TileEntityIronChestRenderer.java:43)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 729567648 bytes (695 MB) / 1783627776 bytes (1701 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2669 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.3.2669.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.3.2669             | forge-1.12.2-14.23.3.2669.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCH   | otgcore              | 1.12.2 - v7              | minecraft.jar                                   | None                                     |
	| UCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCH   | elucore              | 1.0                      | minecraft.jar                                   | None                                     |
	| UCH   | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCH   | quark                | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCH   | animania             | 1.4.7                    | animania-1.12.2-1.4.7.jar                       | None                                     |
	| UCH   | antiqueatlas         | 4.4.7                    | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCH   | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCH   | examplemod           | 1.0                      | antiqueatlas-1.12.2-4.4.7.jar                   | None                                     |
	| UCH   | crafttweaker         | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | mtlib                | 3.0.4                    | MTLib-3.0.4.jar                                 | None                                     |
	| UCH   | modtweaker           | 4.0.10                   | modtweaker-4.0.10.jar                           | None                                     |
	| UCH   | jei                  | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCH   | architecturecraft    | @VERSION@                | architecturecraft-1.12-2.68.jar                 | None                                     |
	| UCH   | autoplant            | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                        | None                                     |
	| UCH   | autoreglib           | 1.3-16                   | AutoRegLib-1.3-16.jar                           | None                                     |
	| UCH   | base                 | 3.7.1                    | base-1.12.2-3.7.1.jar                           | None                                     |
	| UCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | betterunderground    | 1.1.2                    | betterunderground-1.1.2.jar                     | None                                     |
	| UCH   | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | openterraingenerator | v6                       | OpenTerrainGenerator-1.12.2 - v6.jar            | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCH   | biomebundle          | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                    | None                                     |
	| UCH   | blockcraftery        | 0.1.3                    | blockcraftery-0.1.3.jar                         | None                                     |
	| UCH   | bookshelf            | 2.3.541                  | Bookshelf-1.12.2-2.3.541.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chesttransporter     | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCH   | ctm                  | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCH   | chisel               | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | chiselsandbits       | 14.16                    | chiselsandbits-14.16.jar                        | None                                     |
	| UCH   | clumps               | 2.0.0                    | Clumps-3.0.0.jar                                | None                                     |
	| UCH   | codechickenlib       | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | crafttweakerjei      | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
	| UCH   | custommainmenu       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar               | None                                     |
	| UCH   | ptrmodellib          | 1.0.2                    | PTRLib-1.0.2.jar                                | None                                     |
	| UCH   | props                | 2.6.0                    | Decocraft-2.6.0_1.12.2.jar                      | None                                     |
	| UCH   | dirt2path            | 1.7.0                    | dirt2path-1.7.0.jar                             | None                                     |
	| UCH   | dsurround            | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar         | None                                     |
	| UCH   | earthworks           | 1.3.4.3                  | Earthworks-1.12-1.3.6.jar                       | None                                     |
	| UCH   | enderstorage         | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | exoticbirds          | 1.0                      | Exotic Birds 1.12.2-1.4.1.jar                   | None                                     |
	| UCH   | familiarfauna        | 1.0.4                    | FamiliarFauna-1.12.2-1.0.4.jar                  | None                                     |
	| UCH   | fasterladderclimbing | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar           | None                                     |
	| UCH   | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | fenceoverhaul        | 1.3.4                    | FenceOverhaul-1.3.4.jar                         | None                                     |
	| UCH   | flatcoloredblocks    | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
	| UCH   | fluidfunnel          | 1.3.0                    | FluidFunnel-1.12.2-1.3.0.jar                    | None                                     |
	| UCH   | foamfix              | 0.9.7-1.12.2             | foamfix-0.9.7-1.12.2-anarchy.jar                | None                                     |
	| UCH   | limelib              | 1.7.10                   | limelib-1.12.2-1.7.10.jar                       | None                                     |
	| UCH   | furnus               | 2.1.5                    | furnus-1.12.2-2.1.5.jar                         | None                                     |
	| UCH   | gardenstuff          | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                      | None                                     |
	| UCH   | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                           | None                                     |
	| UCH   | harvest              | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                       | None                                     |
	| UCH   | hopperducts          | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCH   | improvedbackpacks    | 1.12.2-1.2.0.2           | ImprovedBackpacks-1.12.2-1.2.0.2.jar            | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks        | 1.12.2-3.0.5-6           | IronBackpacks-1.12.2-3.0.5-6.jar                | None                                     |
	| UCE   | ironchest            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCH   | harvestcraft         | 1.12.2t                  | Pam's HarvestCraft 1.12.2t.jar                  | None                                     |
	| UCH   | jehc                 | 1.12.2                   | JEHC-1.12.2-1.5.0.0.jar                         | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | jeresources          | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCH   | landlust             | 1.12.2-0.3.6             | landlust-1.12.2-0.3.6.jar                       | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCH   | mantle               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCH   | mcmultipart          | 2.4.1                    | MCMultiPart-2.4.1.jar                           | None                                     |
	| UCH   | moreoverlays         | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                  | None                                     |
	| UCH   | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | nex                  | 2.1.14.15                | NetherEx-1.12-2.1.14.15.jar                     | None                                     |
	| UCH   | recipehandler        | 0.10                     | NoMoreRecipeConflict-0.10(1.12.2).jar           | None                                     |
	| UCH   | notenoughroofs       | 0.8.0.0                  | notenoughroofs-1.12.2-0.8.0.0.jar               | None                                     |
	| UCH   | placebo              | 1.3.2                    | Placebo-1.12.2-1.3.2.jar                        | None                                     |
	| UCH   | plants2              | 2.8.2                    | Plants-1.12.2-2.8.2.jar                         | None                                     |
	| UCH   | pcb                  | 1.5.0                    | portablecraftbench-1.12.2-1.5.1.jar             | None                                     |
	| UCH   | potionfingers        | r1.0-2                   | PotionFingers-r1.0-2.jar                        | None                                     |
	| UCH   | reccomplex           | 1.4.7                    | RecurrentComplex-1.4.7.jar                      | None                                     |
	| UCH   | redstonepaste        | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
	| UCH   | resourceloader       | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | rustic               | 1.0.3                    | rustic-1.0.3.jar                                | None                                     |
	| UCH   | signpost             | 1.07.2                   | signpost-1.12-1.07.2.jar                        | None                                     |
	| UCH   | simplyenchanting     | 1.0.3                    | SimplyEnchanting-1.12-1.0.3.jar                 | None                                     |
	| UCH   | soundfilters         | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                  | None                                     |
	| UCH   | sparkshammers        | 1.7.1                    | sparkshammers-1.12.2-1.7.1.jar                  | None                                     |
	| UCH   | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCH   | theoneprobe          | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCH   | topaddons            | 1.12.2-1.5.0             | topaddons-1.12.2-1.5.0.jar                      | None                                     |
	| UCH   | torchmaster          | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCH   | ts2k16               | 1.2.8                    | TS2K16-1.2.8.jar                                | None                                     |
	| UCH   | vt                   | 1.2.11                   | VanillaTweaks-1.2.11.jar                        | None                                     |
	| UCH   | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCH   | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCH   | wholetreeaxe         | 1.7.1                    | WholeTreeAxe-1.12-1.7.1.jar                     | None                                     |
	| UCH   | elulib               | 0.1.12                   | elulib-0.1.12.jar                               | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  org.blockartistry.DynSurround.asm.Transformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by alexbegt** [comment]
I am unable to recreate this issue, If it still occurs please reopen a new ticket! Thanks
