### ISSUE TITLE
IronChests and CarryOn issues

### ISSUE THREAD

**Issue by vico93** [progwml6/ironchest#138]
Hi! I currently having some issues using this mod and [CarryOn](https://minecraft.curseforge.com/projects/carry-on).

Basically, carrying an Iron Chest with items inside always faces west when leaving it on ground.

I reported the issue on CarryOn side (https://github.com/Tschipp/CarryOn/issues/97), but the author closed this as `wontfix` because:

> This is a Problem that occurs when Blocks store their rotation in NBT and not in BlockStates. The same happens with Machines from AE2. Sadly there's nothing I can do about that.

Is there something you can do to remediate this? Thanks in advance!

**Comment by alexbegt** [comment]
This issue will be fixed in 1.13 but I am unable to fix it in 1.12 without breaking existing chests in the process. I am sorry.
