### ISSUE TITLE
Found a virus in the mod

### ISSUE THREAD

**Issue by Salaru** [progwml6/ironchest#141]
For modded minecraft players. My FixMeStick antivirus, once again, found the Java.Adwind.APL.Gen virus within the iron chests mod in the following modpacks. It is likely in more than them. All the Mods 3, Farland Island, Exoria, and World of Dragons, all located on the twitch launcher. Other antivirus programs haven't found it, so it may be a new variation.

**Comment by glasspelican** [comment]
I uploaded [ironchest to virustotal](https://www.virustotal.com/#/file/f7937f561ce87f67e8e436f44651afd2e51c6ace58de5e8fe4dfdd2563794dc0/detection) and it has found no viruses in the mod. Your antivirus is then either the best in the industry (its not) or you are getting a false positive. Alternately you have a dropper on your computer that is attempting to install a backdoor, if this is the case i would recommend downloading and running [Malwarebytes](https://www.malwarebytes.com)

**Comment by Salaru** [comment]
Checked again. And again. It's in the same several modpacks. Some viruses don't get picked up if windows is active, which lets the viruses BE active to dance around detection. Fixmestick runs a scan without loading windows. I have scanned repeatedly. It is not a false positive, and ironchest-1.12.2-7.0.42.827.jar IS INFECTED! At least from wherever it was gotten from by the pack makers.

**Comment by glasspelican** [comment]
then please upload your copy(s) of ironchest to virustotal.com and link us the result, this it probably something you will need to take up with the pack makers.

fixmestick is NOT a good antivirus product, just a heavily marketed one.
I would strongly sugest that you use one of the free products made by actual antivirus companys https://www.lifewire.com/free-bootable-antivirus-tools-2625785

**Comment by pie-flavor** [comment]
Try this.

Download the repository, open a command window inside of it, run `./gradlew setupDecompWorkspace`, and then run `./gradlew build`. Then go to `build/libs`, and run your virus scanner on the resulting jar file.

If that turns up positive, then your virus scanner is simply wrong.

Edit: Actually, I'll save you the trouble - I built [this file](https://dbr.ee/AHWA) locally.
