### ISSUE TITLE
Disappearing Issue

### ISSUE THREAD

**Issue by yepidoodles** [progwml6/ironchest#142]
Hello,

I think this is just a multiplayer issue, so I'm not sure you can do anything about it, but I'd be a crappy server owner if I didn't report it!

Basically, sometimes the contents of Iron Chests will vanish - The items will still be there but they're inaccessible until you close and re-open the chest. I tried to make a GIF of it, but it only happens sometimes, and happens more often when accessed via a Tinkers' Crafting Station. So far I've seen it happen on both Diamond and Gold chests.
[![Screenshot from Gyazo](https://gyazo.com/d979d96ef1825e7fb8aa3e589aaae08c/raw)](https://gyazo.com/d979d96ef1825e7fb8aa3e589aaae08c)

Forge: 2707
SpongeForge: 3135
Iron Chests: 1.12.2-7.0.42.827.jar

~ Alice

**Comment by Draskh** [comment]
I have the same issue in Forge 2705 without Sponge.

**Comment by antisocialian** [comment]
Getting this issue in the All the Mods 3 pack on singleplayer. Using Forge "1.12.2-14.23.4.2705" and Iron Chests "ironchest-1.12.2-7.0.42.827.jar" doesn't always happen in the same length of time for me, it has happened right away as i open the chest, and after a second or two.

The chests still react normal, I can shift+click items out even if I can't see them, I can still pipe items in if there is room. If the items are piped in after the chest as stopped rendering items and I'm still looking in it, the item appears where it should while the rest stays not rendered.

It seems just exiting the inventory and entering again is a temporary (although semi aggravating) fix.

**Comment by Barhandar** [comment]
I am experiencing the issue of items visually vanishing with inventories entirely unrelated to Iron Chest (Thaumcraft's research table, Immersive Engineering's Alloy Kiln). Other mods might be the cause/trigger for this issue. 
How are Iron Chest's inventories/GUIs implemented? How similar is it to IE's (because opensource) way? How _dis_similar is it to Rustic's Pots or Blood Magic's Hellfire Forge is it?

@Sanofus, @yepidoodles do your packs contain Thaumcraft 6? Does this happen if you remove TC6 from the pack? Considering other _ridiculous_ interference it causes (step-assist items failing to work, Akashic Tome turning all tomes added to a single one, etc) it's one of the likely culprits. Also, do they have NEI or only JEI? Crafting Tweaks?

**Comment by Draskh** [comment]
My pack contains Thaumcraft and JEI.

**Comment by yepidoodles** [comment]
My packs don't contain Thaumcraft, and only have JEI.

**Comment by ghost** [comment]
*edited to remove incorrect info*
I'm getting the same exact issue with iron chest 7.0.44.829 on forge 14.23.4.2729. I'm on a singleplayer world and it only seems to do this "disappearing" act on chests that are placed in close proximity to a TC Smelter (3 blocks away or less).

**Comment by kragnoth** [comment]
Ironchests - ironchest-1.12.2-7.0.46.831.jar
and forge 2745

Same exact issue.  Chests are not near anything special.  Don't have any TESR or other non-vanilla rendering items placed in world.  Willing to bet this is a conflict with some other mod and the way iron chests displays the gui.  This does not happen with inventories in other mods like AA chests/etc.

**Comment by smmarkvard** [comment]
I´'ve Got the same error on a continuum multiplayers server. i have also isolated it. Iron chest must be the cause. And it seems to only happen in a specific chunk

**Comment by CourtArtanis** [comment]
Same issue here on a private SMP server:
ironchest-1.12.2-7.0.46.831
Forge 2745

The Iron/Gold chest (not tested with diamond or others) would appear to have to be in the same chunk as a TiC smeltery. Mine is 7x7.

Inventory disappears until updated by the player. Picking up items from or sorting the chest with Inventory Tweaks makes the inventory contents reappear briefly, but adding items to the chest does not.
The addition/removal of a resource pack makes no difference.
![2018-08-21_06 16 50](https://user-images.githubusercontent.com/1242269/44381976-cb11d680-a50a-11e8-975e-5f08beba274d.png)
![2018-08-21_06 28 34](https://user-images.githubusercontent.com/1242269/44382100-7d499e00-a50b-11e8-9371-2e0ea4739978.png)

**Comment by TheFlash787** [comment]
Yep! Same issue here. Engimatica 2: Expert Skyblock.

**Comment by HFinner** [comment]
SAME ISSUE!!!

**Comment by HFinner** [comment]
Correction, I only have this issue when my computer slows down a fair bit and gives my game frame loss. Really odd issue

**Comment by Draskh** [comment]
I have this issue still with Forge 2755.

**Comment by alexbegt** [comment]
If this still occurs with the newest build, please reopen a new ticket.

**Comment by NickelHub** [comment]
Does not occur anymore I think.
