### ISSUE TITLE
Forge 2764 introduces a start crash for IronChests

### ISSUE THREAD

**Issue by vico93** [progwml6/ironchest#148]
Crash log: https://paste.dimdev.org/aqavulapab.mccrash

For a little context [2764](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2764/forge-1.12.2-14.23.4.2764-changelog.txt) was out to [fix some bugs](https://github.com/MinecraftForge/MinecraftForge/commit/93b704b459c6f537d3b1651008c49ce1db2e0ca1) introduced by [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/5160), but now it just crashes IronChests at start.

**Comment by gctypo** [comment]
I can confirm this happens for me as well.

**Comment by Orygeunik** [comment]
Confirmed crash. More error logs: https://gist.github.com/Orygeunik/dc88777c021bbb004f739d60bb8e86e1

**Comment by Draskh** [comment]
I got the same crash. 
[crash-2018-09-28_18.53.48-client.txt](https://github.com/progwml6/ironchest/files/2429045/crash-2018-09-28_18.53.48-client.txt)

**Comment by vico93** [comment]
Apparently this was fixed in b2765. At least this started well here.

From its [changelog](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2765/forge-1.12.2-14.23.4.2765-changelog.txt):
`LexManos: Fix NPE on clientside entities constructed with null world (#5170)` | Relative [PR](https://github.com/MinecraftForge/MinecraftForge/pull/5170)
