### ISSUE TITLE
[1.12.2] Chest(s) may be misreporting capacity

### ISSUE THREAD

**Issue by xenoflot** [progwml6/ironchest#153]
Hi folks,

Playing Enigmatica 2, v1.49. I'm outputting with CoFH's Impulse ducts to diamond chests and the chests won't fill past the half way point. That is, the diamond chest offers a 12 x 9 inventory space. The ducts will fill up to and including the 6th column of the 5th row, then won't insert any more. It's happening both furnace to chest and chest to chest.

I reported to CoFH and KingLemming replied that this would only happen if the chest was misreporting its capacity.

MC 1.12.2
Forge 14.23.4.2751
CoFH Core 4.6.1.22
TDynamics 2.5.3.16
TExpansion 5.5.2.36
TFoundation 2.6.1.22
Iron Chest 7.0.51 build 836

**Comment by alexbegt** [comment]
Can you show me your setup? I am unable to recreate this as in my test area the items go into the chest just fine. Also has the modpack updated to the latest iron chests? I might've fixed this bug already and that's why i can't recreate it

**Comment by alexbegt** [comment]
Update: I did fix this issue in build 837, if you could please update or contact the pack author to update if they haven't! Thanks!

**Comment by xenoflot** [comment]
Many thanks.
