### ISSUE TITLE
Error While Loading (According to MC Forge)

### ISSUE THREAD

**Issue by PendragonII** [progwml6/ironchest#155]
Pastebin website for structured response [here](https://paste.dimdev.org/eqanoqedom.mccrash). I recommend you visit website to view log because the _website understands the language_ and thus **visually accommodating** 
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2018-12-02 19:53:16 EST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Iron Chest (ironchest)
Caused by: java.lang.ExceptionInInitializerError
    at cpw.mods.ironchest.client.ClientProxy.preInit(ClientProxy.java:39)
    at cpw.mods.ironchest.IronChest.preInit(IronChest.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.Entity.setPosition(Entity.java:359)
    at net.minecraft.entity.Entity.<init>(Entity.java:203)
    at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
    at cpw.mods.ironchest.client.renderer.chest.TileEntityIronChestRenderer.<clinit>(TileEntityIronChestRenderer.java:43)
    ... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.15.0-42-generic
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2607226736 bytes (2486 MB) / 3892314112 bytes (3712 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 7 total; -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=160M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2764 121 mods loaded, 121 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                   | Version                  | Source                                          | Signature                                |
       |:----- |:------------------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft                            | 1.12.2                   | minecraft.jar                                   | None                                     |
       | UCH   | mcp                                  | 9.42                     | minecraft.jar                                   | None                                     |
       | UCH   | FML                                  | 8.0.99.99                | forge-1.12.2-14.23.4.2764.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                                | 14.23.4.2764             | forge-1.12.2-14.23.4.2764.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | openmodscore                         | 0.12                     | minecraft.jar                                   | None                                     |
       | UCH   | foamfixcore                          | 7.7.4                    | minecraft.jar                                   | None                                     |
       | UCH   | botania_tweaks_core                  | -100                     | minecraft.jar                                   | None                                     |
       | UCH   | crafttweaker                         | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCH   | mtlib                                | 3.0.5                    | MTLib-3.0.5.jar                                 | None                                     |
       | UCH   | modtweaker                           | 4.0.13                   | modtweaker-4.0.14.jar                           | None                                     |
       | UCH   | jei                                  | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                       | None                                     |
       | UCH   | abyssalcraft                         | 1.9.4.11                 | AbyssalCraft-1.12.2-1.9.4.11.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | UCH   | acintegration                        | 1.6.6                    | AbyssalCraft Integration-1.12.2-1.6.6.jar       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | UCH   | akashictome                          | 1.2-10                   | AkashicTome-1.2-10.jar                          | None                                     |
       | UCH   | animalium                            | 0.3.7                    | Animalium-0.3.7.jar                             | None                                     |
       | UCH   | baubles                              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
       | UCH   | astralsorcery                        | 1.9.4                    | astralsorcery-1.12.2-1.9.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | UCH   | autoreglib                           | 1.3-20                   | AutoRegLib-1.3-20.jar                           | None                                     |
       | UCH   | badwithernocookiereloaded            | 1.12.2-3.1.14            | badwithernocookiereloaded-1.12.2-3.1.14.jar     | None                                     |
       | UCH   | bibliocraft                          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | UCH   | biomesoplenty                        | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
       | UCH   | cyclicmagic                          | 1.16.10                  | Cyclic-1.12.2-1.16.10.jar                       | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | UCH   | guideapi                             | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                     | None                                     |
       | UCH   | bloodmagic                           | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                 | None                                     |
       | UCH   | bloodmoon                            | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCH   | bookshelf                            | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | botania_tweaks                       | 1.7                      | botaniatweaks-1.7.jar                           | None                                     |
       | UCH   | thaumcraft                           | 6.1.BETA24               | Thaumcraft-1.12.2-6.1.BETA24.jar                | None                                     |
       | UCH   | botania                              | r1.10-356                | Botania r1.10-356.jar                           | None                                     |
       | UCH   | chameleon                            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | UCH   | codechickenlib                       | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | chickenchunks                        | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | ctm                                  | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
       | UCH   | chisel                               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
       | UCH   | chunkpregenerator                    | 1.8                      | Chunk Pregenerator V1.12-1.9.jar                | None                                     |
       | UCH   | redstoneflux                         | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | cofhcore                             | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
       | UCH   | cofhworld                            | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | cookiecore                           | 2.0.0                    | cookiecore-1.12-2.0.0.jar                       | 4bbb70ebe391f24f7704e343108a9b21b44c1b10 |
       | UCH   | cosmeticarmorreworked                | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCH   | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCH   | ctgui                                | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCH   | crafttweakerjei                      | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCH   | cyclopscore                          | 0.11.10                  | CyclopsCore-1.12.2-0.11.10.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCH   | darkutils                            | 1.8.211                  | DarkUtils-1.12.2-1.8.211.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | death_compass                        | 0.0.3                    | DeathCompass-0.0.3.jar                          | None                                     |
       | UCH   | defiledlands                         | 1.4.2                    | defiledlands-1.12.2-1.4.2.jar                   | None                                     |
       | UCH   | discordsuite                         | 2.2.4                    | DiscordSuite-2.2.4.jar                          | None                                     |
       | UCH   | disenchanter                         | 1.6                      | disenchanter-[1.12]1.6.jar                      | None                                     |
       | UCH   | dmt                                  | 1.9.3                    | dmt-1.9.3.jar                                   | None                                     |
       | UCH   | dungeonmobs                          | 5.5.0                    | dungeonmobs-5.5.0-MC1.12.2.jar                  | None                                     |
       | UCH   | dsurround                            | 3.4.9.16                 | DynamicSurroundings-1.12.2-3.4.9.16.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | UCH   | presets                              | 3.4.9.16                 | DynamicSurroundings-1.12.2-3.4.9.16.jar         | None                                     |
       | UCH   | ebwizardry                           | 4.1.2                    | Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar  | None                                     |
       | UCH   | enchdesc                             | 1.1.9                    | EnchantmentDescriptions-1.12.2-1.1.9.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | enderzoo                             | 1.12.1-1.4.0.49          | EnderZoo-1.12.1-1.4.0.49.jar                    | None                                     |
       | UCH   | evilcraft                            | 0.10.63                  | EvilCraft-1.12.2-0.10.63.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCH   | evilcraftcompat                      | 1.0.0                    | EvilCraft-1.12.2-0.10.63.jar                    | None                                     |
       | UCH   | fencejumper                          | 1.0.5                    | fencejumper-1.12-1.0.5.jar                      | None                                     |
       | UCH   | findme                               | 1.0.2                    | findme-1.12.2-1.0.2-6.jar                       | None                                     |
       | UCH   | foamfix                              | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                       | None                                     |
       | UCH   | forgivingvoid                        | 1.0.18                   | ForgivingVoid_1.12.2-1.0.18.jar                 | None                                     |
       | UCH   | fw                                   | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
       | UCH   | howlingmoon                          | 0.9                      | howlingmoon-1.12.2-0.9.jar                      | None                                     |
       | UCH   | llibrary                             | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCH   | iceandfire                           | 1.5.2                    | iceandfire-1.5.2.jar                            | None                                     |
       | UCH   | incontrol                            | 0.1.0                    | incontrol-1.12-3.8.1.jar                        | None                                     |
       | UCH   | infernalmobs                         | 1.7.5                    | InfernalMobs-1.12.2.jar                         | None                                     |
       | UCH   | instantunify                         | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                   | None                                     |
       | UCH   | inventorypets                        | 1.5.3.1                  | inventorypets-1.12-1.5.3.1.jar                  | None                                     |
       | UCH   | inventorytweaks                      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCEE  | ironchest                            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
       | UC    | jeiintegration                       | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
       | UC    | journeymap                           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
       | UC    | jeresources                          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
       | UC    | laggoggles                           | FORGE-1.12.2-4.1         | LagGoggles-FORGE-1.12.2-4.1.jar                 | None                                     |
       | UC    | lex                                  | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                          | None                                     |
       | UC    | lootbags                             | 2.5.6                    | LootBags-1.12.2-2.5.6.jar                       | None                                     |
       | UC    | magicfeather                         | @VERSION@                | magicfeather-1.12.1-2.1.0.jar                   | None                                     |
       | UC    | mcjtylib_ng                          | 3.0.5                    | mcjtylib-1.12-3.0.5.jar                         | None                                     |
       | UC    | neat                                 | 1.4-17                   | Neat 1.4-17.jar                                 | None                                     |
       | UC    | hellbound                            | 1.0                      | netherbound-1.2.jar                             | None                                     |
       | UC    | netherbound                          | 1.2                      | netherbound-1.2.jar                             | None                                     |
       | UC    | nex                                  | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                       | None                                     |
       | UC    | thermalfoundation                    | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermalexpansion                     | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | netherfoundation                     | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar     | None                                     |
       | UC    | netherportalfix                      | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar               | None                                     |
       | UC    | nmsot                                | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar         | None                                     |
       | UC    | nei                                  | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.239-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | openmods                             | 0.12                     | OpenModsLib-1.12.2-0.12.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | openblocks                           | 1.8                      | OpenBlocks-1.12.2-1.8.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | parry                                | 1.0                      | parry-1.0-hotfix.jar                            | None                                     |
       | UC    | potioncore                           | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                   | None                                     |
       | UC    | progressivebosses                    | 1.3.2                    | ProgressiveBosses-1.3.2-mc1.12.x.jar            | None                                     |
       | UC    | qualitytools                         | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar               | None                                     |
       | UC    | rftools                              | 7.56                     | rftools-1.12-7.56.jar                           | None                                     |
       | UC    | ftrsquids                            | 1.0.1                    | Rocket+Squids+1.12.2-1.0.1.jar                  | None                                     |
       | UC    | roguelike                            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
       | UC    | roughmobs                            | 2.0.0                    | roughmobs2-1.12.2_2.0.9.jar                     | None                                     |
       | UC    | silentlib                            | 3.0.1                    | SilentLib-1.12.2-3.0.1-145.jar                  | None                                     |
       | UC    | scalinghealth                        | 1.3.26                   | ScalingHealth-1.12.2-1.3.26-127.jar             | None                                     |
       | UC    | storagedrawers                       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
       | UC    | tc6aspects4jei                       | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                       | None                                     |
       | UC    | texfix                               | 4.0                      | TexFix V-1.12-4.0.jar                           | None                                     |
       | UC    | theoneprobe                          | 1.4.24                   | theoneprobe-1.12-1.4.24.jar                     | None                                     |
       | UC    | thermalcultivation                   | 0.3.0                    | ThermalCultivation-1.12.2-0.3.0.7-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermaldynamics                      | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | tickprofiler                         | 1.12-0.0.7               | TickProfiler-1.12-0.0.7.jar                     | None                                     |
       | UC    | tp                                   | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar      | None                                     |
       | UC    | topaddons                            | 1.12.2-1.9.0             | topaddons-1.12.2-1.9.0.jar                      | None                                     |
       | UC    | treechopper                          | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
       | UC    | twilightforest                       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
       | UC    | unlimitedchiselworks                 | 0.2.0                    | UnlimitedChiselWorks-0.2.0.jar                  | None                                     |
       | UC    | vampirism                            | 1.4.5                    | Vampirism-1.12.2-1.4.5.jar                      | None                                     |
       | UC    | teamlapen-lib                        | 1.4.5                    | Vampirism-1.12.2-1.4.5.jar                      | None                                     |
       | UC    | vampirism_integrations               | vampirism_integrations   | VampirismIntegrations-1.12.2-1.0.0.jar          | None                                     |
       | UC    | vanillafix                           | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                         | None                                     |
       | UC    | wanionlib                            | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                        | None                                     |
       | UC    | waystones                            | 4.0.63                   | Waystones_1.12.2-4.0.63.jar                     | None                                     |
       | UC    | unidict                              | 1.12.2-2.7b              | UniDict-1.12.2-2.7b.jar                         | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      AstralCore (astralsorcery-1.12.2-1.9.4.jar)
                                        
                                      CoreMod (TickProfiler-1.12-0.0.7.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Botania Tweaks Core (botaniatweaks-1.7.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
                                        openmods.core.OpenModsClassTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      llibrary (llibrary-core-1.0.8-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
  GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 18.0.5' Renderer: 'AMD ARUBA (DRM 2.50.0 / 4.15.0-42-generic, LLVM 6.0.0)'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Suspected Mods: Iron Chest (ironchest)
  Launched Version: 1.12.2-forge1.12.2-14.23.4.2764
  LWJGL: 2.9.4
  OpenGL: AMD ARUBA (DRM 2.50.0 / 4.15.0-42-generic, LLVM 6.0.0) GL version 3.0 Mesa 18.0.5, X.Org
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Faithful+1.12.2-rv4.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 2x AMD A6-5400K APU with Radeon(tm) HD Graphics

**Comment by alexbegt** [comment]
If you are running a mod pack, please contact the author so that they can upgrade to ironchest-1.12.2-7.0.54.838, you Iron Chest is currently out of date.
