### ISSUE TITLE
Crash on Startup (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by Prang97** [progwml6/ironchest#157]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2018-12-23 00:15:04 AEDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Iron Chest (ironchest)
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.getItem()Lnet/minecraft/item/ItemStack;
    at io.github.strikerrocker.vt.events.VTEventHandler.attachCapabilityEntity(VTEventHandler.java:131)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_546_VTEventHandler_attachCapabilityEntity_AttachCapabilitiesEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:638)
    at net.minecraft.entity.Entity.<init>(Entity.java:219)
    at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
    at cpw.mods.ironchest.client.renderer.chest.TileEntityIronChestRenderer.<clinit>(TileEntityIronChestRenderer.java:52)
    at cpw.mods.ironchest.client.ClientProxy.preInit(ClientProxy.java:39)
    at cpw.mods.ironchest.IronChest.preInit(IronChest.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 230763032 bytes (220 MB) / 1140850688 bytes (1088 MB) up to 12884901888 bytes (12288 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 131 mods loaded, 131 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                        | Version            | Source                                             | Signature                                |
       |:----- |:------------------------- |:------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft                 | 1.12.2             | minecraft.jar                                      | None                                     |
       | UCH   | mcp                       | 9.42               | minecraft.jar                                      | None                                     |
       | UCH   | FML                       | 8.0.99.99          | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                     | 14.23.5.2768       | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | openmodscore              | 0.12.1             | minecraft.jar                                      | None                                     |
       | UCH   | securitycraft             | v1.8.10            | [1.12.2]+SecurityCraft+v1.8.10.jar                 | None                                     |
       | UCH   | aether_legacy             | 1.12.2-v3.2        | aether_legacy-1.12.2-v3.2.jar                      | None                                     |
       | UCH   | jei                       | 4.13.1.225         | jei_1.12.2-4.13.1.225.jar                          | None                                     |
       | UCH   | appleskin                 | 1.0.9              | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | UCH   | appliedenergistics2       | rv6-stable-4       | appliedenergistics2-rv6-stable-4.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | UCH   | aroma1997core             | 2.0.0.0            | Aroma1997Core-1.12.2-2.0.0.0.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCH   | aroma1997sdimension       | 1.3.0.0.b37        | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar  | None                                     |
       | UCH   | baubles                   | 1.5.2              | Baubles-1.12-1.5.2.jar                             | None                                     |
       | UCH   | astralsorcery             | 1.10.3             | astralsorcery-1.12.2-1.10.3.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | UCH   | bettercombatmod           | 1.5.6              | BetterCombat-1.12.2-1.5.6.jar                      | None                                     |
       | UCH   | bibliocraft               | 2.4.5              | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | UCH   | buildcraftlib             | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftcore            | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftenergy          | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | forestry                  | 5.8.2.374          | forestry_1.12.2-5.8.2.374.jar                      | None                                     |
       | UCH   | binniecore                | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | binniedesign              | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | genetics                  | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | botany                    | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | extrabees                 | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | extratrees                | 2.5.1.184          | binnie-mods-1.12.2-2.5.1.184.jar                   | None                                     |
       | UCH   | guideapi                  | 1.12-2.1.7-62      | Guide-API-1.12-2.1.7-62.jar                        | None                                     |
       | UCH   | bloodmagic                | 1.12.2-2.3.3-101   | BloodMagic-1.12.2-2.3.3-101.jar                    | None                                     |
       | UCH   | bookshelf                 | 2.3.568            | Bookshelf-1.12.2-2.3.568.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | thaumcraft                | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | UCH   | botania                   | r1.10-358          | Botania+r1.10-358.jar                              | None                                     |
       | UCH   | codechickenlib            | 3.2.2.353          | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | redstoneflux              | 2.1.0              | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | brandonscore              | 2.4.7              | BrandonsCore-1.12.2-2.4.7.189-universal.jar        | None                                     |
       | UCH   | buildcraftbuilders        | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftfactory         | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftrobotics        | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcrafttransport       | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftsilicon         | 7.99.19            | buildcraft-7.99.19.jar                             | None                                     |
       | UCH   | buildcraftcompat          | 7.99.15            | buildcraft-compat-7.99.15.jar                      | None                                     |
       | UCH   | buildinggadgets           | 2.4.6              | BuildingGadgets-2.4.6.jar                          | None                                     |
       | UCH   | chameleon                 | 1.12-4.1.3         | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | UCH   | chesttransporter          | 2.8.8              | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | UCH   | chickenchunks             | 2.4.1.73           | ChickenChunks-1.12.2-2.4.1.73-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | ctm                       | MC1.12.2-0.3.3.22  | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | UCH   | chisel                    | MC1.12.2-0.2.1.35  | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | UCH   | cofhcore                  | 4.6.1              | CoFHCore-1.12.2-4.6.1.22-universal.jar             | None                                     |
       | UCH   | cofhworld                 | 1.3.0              | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | computercraft             | 1.80pr1            | ComputerCraft1.80pr1.jar                           | None                                     |
       | UCH   | controlling               | 3.0.6              | Controlling-3.0.6.jar                              | None                                     |
       | UCH   | cookingforblockheads      | 6.4.65             | CookingForBlockheads_1.12.2-6.4.65.jar             | None                                     |
       | UCH   | cucumber                  | 1.1.2              | Cucumber-1.12.2-1.1.2.jar                          | None                                     |
       | UCH   | waila                     | 1.8.26             | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | UCH   | darkutils                 | 1.8.218            | DarkUtils-1.12.2-1.8.218.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | diethopper                | 1.1                | diethopper-1.1.jar                                 | None                                     |
       | UCH   | doggytalents              | 1.14.2.380         | Doggy+Talents-1.12.2-1.14.2.380-universal.jar      | None                                     |
       | UCH   | thermalfoundation         | 2.6.1              | ThermalFoundation-1.12.2-2.6.1.22-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | draconicevolution         | 2.3.17             | Draconic-Evolution-1.12.2-2.3.17.321-universal.jar | None                                     |
       | UCH   | llibrary                  | 1.7.15             | llibrary-1.7.15-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCH   | dragonmounts              | 1.12.2-1.4.9.2     | DragonMounts-1.12.2-1.4.9.2.jar                    | None                                     |
       | UCH   | enderstorage              | 2.4.5.135          | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | extracells                | 2.6.1              | ExtraCells-1.12.2-2.6.1a.jar                       | None                                     |
       | UCH   | extrautils2               | 1.0                | extrautils2-1.12-1.9.8.jar                         | None                                     |
       | UCH   | zerocore                  | 1.12-0.1.2.2       | zerocore-1.12-0.1.2.2.jar                          | None                                     |
       | UCH   | bigreactors               | 1.12.2-0.4.5.49    | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
       | UCH   | fastfurnace               | 1.2.1              | FastFurnace-1.12.2-1.2.1.jar                       | None                                     |
       | UCH   | fastleafdecay             | v14                | FastLeafDecay-v14.jar                              | None                                     |
       | UCH   | fastbench                 | 1.6.0              | FastWorkbench-1.12.2-1.6.0.jar                     | None                                     |
       | UCH   | forgemultipartcbe         | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | microblockcbe             | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
       | UCH   | minecraftmultipartcbe     | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
       | UCH   | gravestone                | 1.3.1              | GraveStone-1.12.2-Graves-1.3.1.jar                 | None                                     |
       | UCH   | gravestone-extended       | 1.3.5              | GraveStone-1.12.2-Extended-1.3.5.jar               | None                                     |
       | UCH   | hammercore                | 2.0.4.0            | HammerCore-1.12.2-2.0.4.0.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | iblis                     | 1.0.8              | iblis-headshots-1.0.8.jar                          | None                                     |
       | UCH   | ichunutil                 | 7.1.4              | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
       | UCH   | twilightforest            | 3.8.689            | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
       | UCH   | immersiveengineering      | 0.12-86            | ImmersiveEngineering-0.12-86.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCH   | immersivepetroleum        | 1.1.9              | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
       | UCH   | immersivetech             | 1.3.10             | immersivetech-1.12-1.3.10.jar                      | None                                     |
       | UCH   | inventorysorter           | 1.13.3+57          | inventorysorter-1.12.2-1.13.3+57.jar               | None                                     |
       | UCEE  | ironchest                 | 1.12.2-7.0.54.838  | ironchest-1.12.2-7.0.54.838.jar                    | None                                     |
       | UC    | harvestcraft              | 1.12.2z            | Pam's+HarvestCraft+1.12.2za.jar                    | None                                     |
       | UC    | jehc                      | 1.12.2             | JEHC-1.12.2-1.6.2.0.jar                            | None                                     |
       | UC    | jeibees                   | 0.9.0.5            | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
       | UC    | journeymap                | 1.12.2-5.5.3       | journeymap-1.12.2-5.5.3.jar                        | None                                     |
       | UC    | jeresources               | 0.8.5.27           | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
       | UC    | kleeslabs                 | 5.4.11             | KleeSlabs_1.12.2-5.4.11.jar                        | None                                     |
       | UC    | magicbees                 | 1.0                | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
       | UC    | mekanism                  | 1.12.2-9.4.13.349  | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | UC    | modularforcefieldsystem   | 3.0.1              | MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar               | None                                     |
       | UC    | moreoverlays              | 1.14               | moreoverlays-1.14-mc1.12.2.jar                     | None                                     |
       | UC    | morpheus                  | 1.12-3.3.2         | Morpheus-1.12-3.3.2.jar                            | None                                     |
       | UC    | mrtjpcore                 | 2.1.3.35           | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
       | UC    | mysticalagriculture       | 1.6.13             | MysticalAgriculture-1.12-1.6.13.jar                | None                                     |
       | UC    | openmods                  | 0.12.1             | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | openblocks                | 1.8                | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | portalgun                 | 7.0.2              | PortalGun-1.12.2-7.0.2.jar                         | None                                     |
       | UC    | projectred-core           | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
       | UC    | projectred-compat         | 1.0                | ProjectRed-1.12.2-4.9.1.92-compat.jar              | None                                     |
       | UC    | projectred-integration    | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
       | UC    | projectred-transmission   | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
       | UC    | projectred-fabrication    | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-fabrication.jar         | None                                     |
       | UC    | projectred-illumination   | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-lighting.jar            | None                                     |
       | UC    | projectred-expansion      | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | UC    | projectred-relocation     | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | UC    | projectred-transportation | 4.9.1.92           | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | UC    | randomtweaks              | 1.12.2-2.2.0.3     | randomtweaks-1.12.2-2.2.0.3.jar                    | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | UC    | reborncore                | 3.10.6.355         | RebornCore-1.12.2-3.10.6.355-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | UC    | thermalexpansion          | 5.5.2              | ThermalExpansion-1.12.2-5.5.2.39-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | redstonearsenal           | 2.6.1              | RedstoneArsenal-1.12.2-2.6.1.15-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | roost                     | 1.3.0              | roost-1.12-1.3.0.jar                               | None                                     |
       | UC    | sgcraft                   | 1.13.2             | SGCraft-1.3-mc1.12.2.jar                           | None                                     |
       | UC    | solarflux                 | 4.16r              | SolarFluxReborn_1.12.2-4.16r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UC    | stevescarts               | 2.4.27.127         | StevesCarts-1.12.2-2.4.27.127.jar                  | None                                     |
       | UC    | storagedrawers            | 1.12-5.3.5         | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
       | UC    | storagedrawersextra       | @VERSION@          | StorageDrawersExtras-1.12-3.1.0.jar                | None                                     |
       | UC    | tc6aspects4jei            | 0.0.2a             | tc6aspects4jei-0.0.2a.jar                          | None                                     |
       | UC    | tcinventoryscan           | 2.0.10             | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
       | UC    | thaumictinkerer           | 1.12.2-5.0-353c71c | thaumictinkerer-1.12.2-5.0-353c71c.jar             | None                                     |
       | UC    | thermalcultivation        | 0.3.1              | ThermalCultivation-1.12.2-0.3.1.8-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermaldynamics           | 2.5.3              | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermalinnovation         | 0.3.1              | ThermalInnovation-1.12.2-0.3.1.8-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | translocators             | 2.5.1.77           | Translocators-1.12.2-2.5.1.77-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | vanillafix                | 1.0.10-SNAPSHOT    | VanillaFix-1.0.10-99.jar                           | None                                     |
       | UC    | wanionlib                 | 1.12.2-1.9         | WanionLib-1.12.2-1.9.jar                           | None                                     |
       | UC    | wawla                     | 2.5.265            | Wawla-1.12.2-2.5.265.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | wearsfr                   | 15b                | WearableSolars-1.12.2-15b.jar                      | None                                     |
       | UC    | wrcbe                     | 2.3.1              | WR-CBE-1.12.2-2.3.1.30-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | vt                        | 1.4.2              | VanillaTweaks-1.4.2.jar                            | None                                     |
       | UC    | unidict                   | 1.12.2-2.9.1       | UniDict-1.12.2-2.9.1.jar                           | None                                     |
  Loaded coremods (and transformers): AstralCore (astralsorcery-1.12.2-1.10.3.jar)
                                        
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.4.0.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      llibrary (llibrary-core-1.0.8-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv6-stable-4 for Forge 14.23.5.2768
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 540 names; 1205 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Wearable Solars (wearsfr) @15b
  Suspected Mods: Vanilla Tweaks (vt), Iron Chest (ironchest)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.34, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Soartex_Fanver_Modded_Universal.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by alexbegt** [comment]
This is related to VanillaTweaks. Please report it here https://github.com/strikerrocker/VanillaTweaks
