### ISSUE TITLE
Disappearing inventories

### ISSUE THREAD

**Issue by CourtArtanis** [progwml6/ironchest#162]
Hi,
The disappearing inventory issue #142 still persists in the latest version ironchest-1.12.2-7.0.55.839
Issue also reported here https://github.com/SlimeKnights/TinkersConstruct/issues/3670

Using:
TConstruct-1.12.2-2.12.0.113
Mantle-1.12-1.3.3.39
forge-1.12.2-14.23.5.2768
ironchest-1.12.2-7.0.55.839

The issue is the same as before. Any Ironchest in a chunk containing smeltery controller has an inventory that disappears until it's updated.
Strangely enough, the issue is also present in Immersive Engineering with the wooden crate, but so far no issues detected in my other mods that add chests and crates.

It can be reliably reproduced with the above setup in SP and MP, any size smeltery (although I'm using 7x7 currently). 
It seems to take 7-10 seconds to disappear after updating the inventory.
It seems as though the actual controller has to be in the same chunk as an ironchest. Seared blocks/tanks that happen to overlap into other chunks don't effect ironchests in those chunks.

**Comment by Freebi85** [comment]
I can confirm this. Also with shulkerboxes :/

**Comment by mrdeadlocked** [comment]
This very frustrating and happens a lot.

**Comment by katubug** [comment]
I'm also having this issue.

TConstruct-1.12.2-2.12.0.135
ironchest-1.12.2-7.0.59.842
Mantle-1.12-1.3.3.49
forge-1.12.2-14.23.5.2825

**Comment by alexbegt** [comment]
What size smeltery are you guys running?

**Comment by Psithief** [comment]
3x3 base plus 5 high walls, for a bounding box of 6 blocks high, 5 blocks wide, 5 blocks deep.

But I am having the problem where the inventory disappears after a few seconds of opening the chest. And it happens in adjacent chunks too. I'm very happy to have found this issue though, because I can just destroy the smeltery.

**Comment by Draskh** [comment]
It happens to me with a 11x11x5 Smeltery and obsidian chests.
