### ISSUE TITLE
Weird Warning in Log File

### ISSUE THREAD

**Issue by TheOriginalEpic** [progwml6/ironchest#165]
**I'm pretty sure its probably nothing to worry about or its probably been resolved already** but every time i run get these warnings in the log window

![2019-01-21](https://user-images.githubusercontent.com/32038605/51511373-6f0fee80-1dd7-11e9-9ec6-d92631670a29.png)

_"Mod ironchest is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-7.0.56.840"_

It intrigued me so I went digging, i extracted the ironchest.jar file to find this

![2019-01-21 1](https://user-images.githubusercontent.com/32038605/51511500-e6de1900-1dd7-11e9-910a-70ddf3a2fca8.png)

it clearly lists the version.properties right there I even opened the file and it has all of the correct documentation

![2019-01-21 2](https://user-images.githubusercontent.com/32038605/51511544-0f661300-1dd8-11e9-8f8a-5d0b90c2c8ee.png)

The other mods don't seem to have this version.properties though

What I want explained though is as to why the iron chest mod is giving this warning when  version.properties exists

**Comment by progwml6** [comment]
its forge giving the warning, the file being setup this way instead of using metadata is an artifact of how CPW setup gradle initially, we will change this for 1.13
