### ISSUE TITLE
Crash when using pistons

### ISSUE THREAD

**Issue by Abattoir19** [progwml6/ironchest#171]
as the title says, CTD when using pistons.

**Comment by progwml6** [comment]
what MC version?

**Comment by linxuanm** [comment]
1.13.2.

This seems like forge's issue rather than the mod's issue. Trying to move a tile entity with piston causes a crash (tested with vanilla chest).

Already reported on the Forge forum.

**Comment by Jaumoso** [comment]
Same issue with the pistons.
Tested with different forge versions and it crashes, so i think its not a forge problem.
MC version: 1.13.2
Forge version: 25.0.82
Here the crash report: (https://github.com/progwml6/ironchest/files/2968270/crash-2019-03-14_11.04.15-client.txt)

**Comment by alexbegt** [comment]
This is an issue on forges end, It was fixed with https://github.com/MinecraftForge/MinecraftForge/commit/8045e48952667b3bcaae2138612e4d41f94bda23. Please update to Forge Version 25.0.88 to fix this crash.
