### ISSUE TITLE
Frame loss due to overlay 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [progwml6/ironchest#172]
## Version Information
`Minecraft: `1.12.2
`Forge: `2822
`Iron Chests: `1.1.0

## Report Information
I noticed that the overlay is draining FPS very much. Measured by the mod and was right. When I take a jet pack, the FPS grows by 100 frames.

https://i.gyazo.com/a10f56d9767583a93140421290de510a.png

**Comment by alexbegt** [comment]
This is related to Iron Jetpacks and not Iron Chests, I would report this to the mod developer.
