### ISSUE TITLE
Minecraft does not start, crash

### ISSUE THREAD

**Issue by SipaiL** [progwml6/ironchest#181]
Version Information
`Minecraft:`1.12.2
`Modpack:`Life in the village
`Forge:`14.23.5.2800
`Iron Chests:`1.12.2-7.0.59.842
Hello, when you start this modpack with the iron chest mod, an error popped up that minecraft cannot start and announces the iron chest mod as a possible reason. What can you do about it? Here is the link from the crash report: https://paste.dimdev.org/halelecezu.mccrash

**Comment by alexbegt** [comment]
Duplicate of #178 which has been fixed. Please either update IronChests to version 7.0.64.843 yourself or talk to the modpack creator to get IronChests updated to the latest version. Thank you
