### ISSUE TITLE
shulker box crash v2

### ISSUE THREAD

**Issue by resinate** [progwml6/ironchest#183]
version: 1.12.2 - ironchest-1.12.2-7.0.67.844.jar
https://pastebin.com/ZwDh182Q

the crash does not happen on version ironchest-1.12.2-7.0.67.843.jar

**Comment by alexbegt** [comment]
Do you happen to have a loot table on your shulker box? Also, what were you doing when this crash occurred?

**Comment by alexbegt** [comment]
Please try with 845 when it's published, if this still occurs; please open a new ticket.
