### ISSUE TITLE
Tcon Bug

### ISSUE THREAD

**Issue by GhEppIO82** [progwml6/ironchest#186]
The long time bug of inventories disappearing when the chests are in the same chunk as a tinker's smeltery.

BRO the BUG persist..

**Comment by alexbegt** [comment]
What version of Iron Chests are you running, Next time; Please give all details that are requested when you open a ticket.

**Comment by GhEppIO82** [comment]
Ultimate update of iron chest and forge  2836

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Alexander (alexbegt) <notifications@github.com>
Inviato: Sunday, June 16, 2019 7:42:28 PM
A: progwml6/ironchest
Cc: GhEppIO82; Author
Oggetto: Re: [progwml6/ironchest] Tcon Bug (#186)


What version of Iron Chests are you running, Next time; Please give all details that are requested when you open a ticket.

**Comment by alexbegt** [comment]
Ultimate version? Do you mean the latest version?

**Comment by GhEppIO82** [comment]
Yes the latest bro,sorry for my english


Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [progwml6/ironchest] Tcon Bug (#186)
Da: "Alexander (alexbegt)"
A: progwml6/ironchest
CC: GhEppIO82 ,Author


Ultimate version? Do you mean the latest version?

**Comment by alexbegt** [comment]
Okay, you are running ironchest-1.12.2-7.0.69.845, Are you able to give me a screenshot of how big your smeltery is which causes the GUI issues?

**Comment by GhEppIO82** [comment]
It’s a simple 3x3x6, and as soon as I am at home I post you a screenshoot


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Alexander (alexbegt) <notifications@github.com>
Inviato: Monday, June 17, 2019 12:10:53 AM
A: progwml6/ironchest
Cc: GhEppIO82; Author
Oggetto: Re: [progwml6/ironchest] Tcon Bug (#186)


So you are running ironchest-1.12.2-7.0.69.845, Are you able to give me a screenshot of how big your smeltery is which causes the GUI issues?

**Comment by GhEppIO82** [comment]
![2019-06-19_18 41 04](https://user-images.githubusercontent.com/45314651/59784479-cf418880-92c2-11e9-9439-060062496800.png)
![2019-06-19_18 41 37](https://user-images.githubusercontent.com/45314651/59784481-cf418880-92c2-11e9-91db-268aa0edd939.png)
this is the screenshot dude,I hope you can solve......

**Comment by GhEppIO82** [comment]
i change the iron chest in crate for the bug

**Comment by alexbegt** [comment]
Please try ironchest-1.12.2-7.0.71.846 when it goes live on curseforge to see if the smeltery bug is finally fixed.

**Comment by GhEppIO82** [comment]
Now is perfect good job dude

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Alexander (alexbegt) <notifications@github.com>
Inviato: Saturday, July 20, 2019 4:06:52 AM
A: progwml6/ironchest <ironchest@noreply.github.com>
Cc: GhEppIO82 <zukkumon@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [progwml6/ironchest] Tcon Bug (#186)


Please try ironchest-1.12.2-7.0.71.846 when it goes live on curseforge to see if the smeltery bug is finally fixed.

**Comment by alexbegt** [comment]
Since this has been fixed I am going to close this.
