### ISSUE TITLE
Crash on Opening Iron Chest

### ISSUE THREAD

**Issue by PapaZ810** [progwml6/ironchest#187]
## Version Information
`Minecraft: 1.12.2`
`Forge: 2836`
`Iron Chests: 1.12.2-7.0.69.845`

## Report Information

The game crashes everytime I try to open an iron chest
## Steps to Reproduce

1. Place iron chest
2. Open it
3. Crash
## Crash Log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  CoreModBase (ShulkerBoxViewer-1.5-mc[1.11-1.12.2].jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/7/19 1:47 PM
Description: Unexpected error

java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at cpw.mods.ironchest.common.blocks.chest.BlockIronChest.func_180639_a(BlockIronChest.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cpw.mods.ironchest.common.blocks.chest.BlockIronChest.func_180639_a(BlockIronChest.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Z810'/84480, l='MpServer', x=-380.14, y=76.00, z=703.60]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-46,64,283), Chunk: (at 2,4,11 in -3,17; contains blocks -48,0,272 to -33,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13985151 game time, 8055777 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntitySquid['Squid'/86275, l='MpServer', x=-360.39, y=58.08, z=667.64], EntityOcelot['Jerry'/84742, l='MpServer', x=-431.27, y=30.66, z=652.45], EntityCreeper['Creeper'/87313, l='MpServer', x=-414.83, y=43.00, z=766.56], EntitySkeleton['Skeleton'/87315, l='MpServer', x=-409.50, y=45.00, z=759.50], EntityZombie['Zombie'/87314, l='MpServer', x=-409.50, y=45.00, z=760.50], EntitySkeleton['Skeleton'/87316, l='MpServer', x=-407.50, y=45.00, z=762.50], EntityChicken['Chicken'/84504, l='MpServer', x=-445.10, y=69.00, z=703.62], EntityBat['Bat'/86818, l='MpServer', x=-359.63, y=23.18, z=724.37], EntityBat['Bat'/87076, l='MpServer', x=-363.46, y=26.93, z=646.52], EntitySpider['Spider'/87596, l='MpServer', x=-363.50, y=24.00, z=645.50], EntitySkeleton['Skeleton'/87089, l='MpServer', x=-372.79, y=49.00, z=712.27], EntitySkeleton['Skeleton'/87088, l='MpServer', x=-371.50, y=49.00, z=711.50], EntitySkeleton['Skeleton'/87091, l='MpServer', x=-375.43, y=49.00, z=711.66], EntitySkeleton['Skeleton'/87090, l='MpServer', x=-375.50, y=49.00, z=713.50], EntityZombie['Zombie'/86586, l='MpServer', x=-347.50, y=27.00, z=669.50], EntitySkeleton['Skeleton'/86845, l='MpServer', x=-345.50, y=27.00, z=700.50], EntitySquid['Squid'/86335, l='MpServer', x=-364.01, y=54.20, z=646.54], EntityBat['Bat'/87361, l='MpServer', x=-452.22, y=34.83, z=736.38], EntitySkeleton['Skeleton'/86852, l='MpServer', x=-351.50, y=19.00, z=642.50], EntitySquid['Squid'/86349, l='MpServer', x=-357.24, y=44.66, z=655.66], EntitySquid['Squid'/86350, l='MpServer', x=-358.20, y=45.75, z=654.50], EntitySkeleton['Skeleton'/84816, l='MpServer', x=-349.50, y=30.00, z=691.50], EntitySkeleton['Skeleton'/86608, l='MpServer', x=-364.29, y=68.00, z=689.51], EntityPlayerSP['Z810'/84480, l='MpServer', x=-380.14, y=76.00, z=703.60], EntitySkeleton['Skeleton'/85848, l='MpServer', x=-358.50, y=14.00, z=688.50], EntityZombie['Zombie'/86872, l='MpServer', x=-355.50, y=40.00, z=746.50], EntityBlaze['Blaze'/87389, l='MpServer', x=-437.50, y=46.20, z=677.11], EntityBat['Bat'/86885, l='MpServer', x=-385.28, y=37.00, z=715.00], EntityBat['Bat'/86884, l='MpServer', x=-311.75, y=31.07, z=785.70], EntityItem['item.item.actuallyadditions.item_hairy_ball'/87140, l='MpServer', x=-430.72, y=30.29, z=652.99], EntityCreeper['Creeper'/85617, l='MpServer', x=-365.60, y=23.00, z=638.84], EntitySkeleton['Skeleton'/86897, l='MpServer', x=-342.50, y=14.00, z=669.50], EntityCreeper['Creeper'/87155, l='MpServer', x=-417.50, y=44.00, z=763.50], EntityBat['Bat'/86386, l='MpServer', x=-352.25, y=30.03, z=741.25], EntityCreeper['Creeper'/87154, l='MpServer', x=-419.50, y=44.00, z=765.50], EntityZombie['Zombie'/85881, l='MpServer', x=-319.50, y=20.00, z=707.50], EntityZombie['Zombie'/86904, l='MpServer', x=-361.50, y=25.00, z=652.50], EntitySkeleton['Skeleton'/87418, l='MpServer', x=-411.50, y=69.00, z=740.50], EntityZombie['Zombie'/87426, l='MpServer', x=-312.50, y=33.00, z=686.50], EntityItem['item.item.blazeRod'/84625, l='MpServer', x=-439.94, y=47.00, z=677.17], EntityBat['Bat'/87185, l='MpServer', x=-357.40, y=26.10, z=649.34], EntityCreeper['Creeper'/85904, l='MpServer', x=-347.50, y=18.00, z=645.50], EntitySkeleton['Skeleton'/86679, l='MpServer', x=-364.50, y=24.00, z=646.50], EntityZombie['Zombie'/86678, l='MpServer', x=-364.50, y=24.00, z=645.50], EntityChicken['Chicken'/84634, l='MpServer', x=-446.11, y=69.00, z=704.38], EntityCreeper['Creeper'/86953, l='MpServer', x=-373.47, y=50.00, z=716.27], EntitySkeleton['Skeleton'/87209, l='MpServer', x=-381.97, y=29.00, z=716.50], EntitySkeleton['Skeleton'/87465, l='MpServer', x=-378.21, y=26.00, z=717.51], EntitySpider['Spider'/86184, l='MpServer', x=-401.50, y=36.00, z=768.50], EntityCreeper['Creeper'/87208, l='MpServer', x=-382.70, y=29.00, z=716.50], EntitySkeleton['Skeleton'/87211, l='MpServer', x=-380.50, y=29.00, z=717.50], EntitySkeleton['Skeleton'/87210, l='MpServer', x=-380.50, y=29.00, z=712.50], EntityBlizz['Blizz'/87466, l='MpServer', x=-375.97, y=25.00, z=716.92], EntitySpider['Spider'/86701, l='MpServer', x=-385.50, y=20.00, z=650.50], EntitySpider['Spider'/86700, l='MpServer', x=-392.02, y=21.00, z=649.99], EntityBat['Bat'/87475, l='MpServer', x=-375.25, y=21.10, z=627.50], EntitySkeleton['Skeleton'/84921, l='MpServer', x=-348.50, y=31.00, z=688.50], EntitySkeleton['Skeleton'/87225, l='MpServer', x=-312.50, y=44.00, z=783.50], EntityZombie['Zombie'/87484, l='MpServer', x=-350.50, y=31.00, z=692.50], EntityCreeper['Creeper'/86720, l='MpServer', x=-359.50, y=22.00, z=633.50], EntityBat['Bat'/86466, l='MpServer', x=-346.25, y=21.10, z=637.25], EntityCreeper['Creeper'/86981, l='MpServer', x=-392.50, y=38.00, z=651.50], EntityZombie['Zombie'/87001, l='MpServer', x=-404.50, y=71.00, z=743.50], EntityZombie['Zombie'/87003, l='MpServer', x=-400.50, y=71.00, z=747.50], EntityCreeper['Creeper'/86490, l='MpServer', x=-417.50, y=44.00, z=762.50], EntityBat['Bat'/87518, l='MpServer', x=-384.21, y=37.12, z=716.51], EntityBat['Bat'/87521, l='MpServer', x=-311.93, y=31.23, z=783.74], EntityWolf['Wolf'/84706, l='MpServer', x=-433.76, y=65.00, z=637.86], EntityBat['Bat'/87522, l='MpServer', x=-299.14, y=19.17, z=705.39], EntityWolf['Wolf'/84733, l='MpServer', x=-451.27, y=68.00, z=656.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:527)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1604655832 bytes (1530 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_C5 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                               | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2836.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2836             | forge-1.12.2-14.23.5.2836.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | obfuscate                         | 0.2.6                    | minecraft.jar                                        | None                                     |
	| LCHIJA | bspkrscore                        | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar               | None                                     |
	| LCHIJA | treecapitator                     | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar                | None                                     |
	| LCHIJA | fastbench                         | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                       | None                                     |
	| LCHIJA | actuallyadditions                 | 1.12.2-r148              | ActuallyAdditions-1.12.2-r148.jar                    | None                                     |
	| LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LCHIJA | actuallybaubles                   | 1.1                      | ActuallyBaubles-1.12-1.1.jar                         | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                         | None                                     |
	| LCHIJA | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                        | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.57            | EnderCore-1.12.2-0.5.57.jar                          | None                                     |
	| LCHIJA | jei                               | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar               | None                                     |
	| LCHIJA | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.12.0.156        | TConstruct-1.12.2-2.12.0.156.jar                     | None                                     |
	| LCHIJA | p455w0rdslib                      | 2.2.151                  | p455w0rdslib-1.12.2-2.2.151.jar                      | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                          | 1.0.30                   | AE2WTLib-1.12.2-1.0.30.jar                           | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | applecore                         | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
	| LCHIJA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| LCHIJA | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LCHIJA | cdm                               | 0.4.1                    | cdm-0.4.1-mc1.12.2.jar                               | None                                     |
	| LCHIJA | cfm                               | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                               | None                                     |
	| LCHIJA | cgm                               | 0.12.1                   | cgm-0.12.1-mc1.12.2.jar                              | None                                     |
	| LCHIJA | chiseledadditions                 | @Version@                | ChiseledAdditions-1.0.0.jar                          | None                                     |
	| LCHIJA | chiselsandbits                    | 14.33                    | chiselsandbits-14.33 (1).jar                         | None                                     |
	| LCHIJA | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                     | None                                     |
	| LCHIJA | controlling                       | 3.0.6                    | Controlling-3.0.6.jar                                | None                                     |
	| LCHIJA | ptrmodellib                       | 1.0.4                    | PTRLib-1.0.4.jar                                     | None                                     |
	| LCHIJA | props                             | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                           | None                                     |
	| LCHIJA | enderiobase                       | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                            | None                                     |
	| LCHIJA | fastfurnace                       | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                         | None                                     |
	| LCHIJA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                      | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                          | None                                     |
	| LCHIJA | jee                               | 1.0.7                    | JustEnoughEnergistics-1.12.2-1.0.7.jar               | None                                     |
	| LCHIJA | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar              | None                                     |
	| LCHIJA | jmcm                              | 9.2                      | MinecraftCapes Forge 1.12.2.jar                      | None                                     |
	| LCHIJA | moreoverlays                      | 1.12                     | moreoverlays-1.12-mc1.12.jar                         | None                                     |
	| LCHIJA | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                        | None                                     |
	| LCHIJA | netherfoundation                  | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar          | None                                     |
	| LCHIJA | overpoweredarmorbar               | @VERSION@                | overloadedarmorbar-1.0.4g.jar                        | None                                     |
	| LCHIJA | harvestcraft                      | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCHIJA | shulkerboxviewer                  | 1.5                      | ShulkerBoxViewer-1.5-mc[1.11-1.12.2].jar             | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | simplyjetpacks                    | 2.2.12.65                | SimplyJetpacks2-1.12.2-2.2.12.65.jar                 | None                                     |
	| LCHIJA | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                          | None                                     |
	| LCHIJA | thermalcultivation                | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaltinkering                  | 1.0                      | ThermalTinkering-1.12.2-2.0.1.jar                    | None                                     |
	| LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
	| LCHIJA | topaddons                         | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                          | None                                     |
	| LCHIJA | trashslot                         | 8.4.10                   | TrashSlot_1.12.2-8.4.10.jar                          | None                                     |
	| LCHIJA | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LCHIJA | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| LCHIJA | wanionlib                         | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                             | None                                     |
	| LCHIJA | wawla                             | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones                         | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                          | None                                     |
	| LCHIJA | weirdinggadget                    | 1.0                      | weirdinggadget-1.12.2-2.1.16-universal.jar           | None                                     |
	| LCHIJA | wct                               | 3.12.93                  | WirelessCraftingTerminal-1.12.2-3.12.93.jar          | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  p455w0rdslib.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CoreModBase (ShulkerBoxViewer-1.5-mc[1.11-1.12.2].jar)
  com.dazo66.shulkerboxshower.asm.MainTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1070 Ti/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r148.jar
		* ae2wtlib|API (1.0.30) from AE2WTLib-1.12.2-1.0.30.jar
		* AppleCoreAPI (3.2.0) from AppleCore-mc1.12.2-3.2.0.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselsAndBitsAPI (14.25.0) from chiselsandbits-14.33 (1).jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.3.27-universal.jar
		* CSLib|API (1.0.1) from PTRLib-1.0.4.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.44.jar
		* jeresources|API (0.9.2.60) from JustEnoughResources-1.12.2-0.9.2.60.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.4.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.268.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.2.647+b31535a.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.12.93.jar
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2836
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Lithos-Core+v1.23+for+1.12x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600X Six-Core Processor

**Comment by alexbegt** [comment]
What block do you have above the chest?

**Comment by PapaZ810** [comment]
There is nothing above the chest

**Comment by alexbegt** [comment]
Are you running a modpack or just mods you chose to use?

**Comment by PapaZ810** [comment]
Mods I choose to use. A modpack of my own creation. Is there a config option that I am missing?

**Comment by PapaZ810** [comment]
I have just discovered that the Iron shulker boxes work perfectly fine. So I suspect that it is an error with rendering the opening of the chest that is crashing the game.

**Comment by PapaZ810** [comment]
It even crashes the game when I have the diamond chest with a block on top of it.

**Comment by alexbegt** [comment]
Can you tell me if it crashes with ironchest-1.12.2-7.0.64.843.jar

**Comment by PapaZ810** [comment]
843 works
