### ISSUE TITLE
Crash after adding item to inventory of iron shulkerbox

### ISSUE THREAD

**Issue by onejk** [progwml6/ironchest#189]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 14.23.5.2836
`Iron Chests: ` ironchest-1.12.2-7.0.69.845.jar

## Report Information

The game crashes anytime I mouse of the ironchest shulker box in my inventory

## Steps to Reproduce

Received ironchest shulker box as quest loot reward from Enigmatica 2 Expert 1.65d
Take bucket of lava and drop into inventory of shulker box (in my inventory)
Game Crashes
Restart
Move around
Hover over shulker box to render tooltip - Crashes

## Crash Log

<script src="https://gist.github.com/onejk/78f66415d30365da2baee5b6862f5f45.js"></script>

**Comment by onejk** [comment]
Further restarts and logins I can move around but crash when opening my inventory or interacting with any other block inventory

**Comment by guiguilyon** [comment]
I have the same problem. Although further restarts and login don't crash my game when opening inventory, as long as I don't hover over the ironchest shulker box.

I tried editing my inventory using Universal Minecraft Editor. But the change is somehow reverted whenever I load the modified save in the game.

So as a workaround I just droped my whole inventory in a chest, carefully avoiding to hover over the buggy item. I then opened the chat and typed /clear. That clears the whole inventory! That deleted the buggy chest. ANd I can play again now! :)

**Comment by alexbegt** [comment]
Can you post your crash report? Unable to view the other one

**Comment by onejk** [comment]
https://drive.google.com/file/d/1y7Bdtrd0xXa3Zumkaav3idO_qyrkp6Yo/view?usp=sharing

**Comment by alexbegt** [comment]
Please upgrade to the latest version of Quark, this was a bug on their side and not our side; Version Quark-r1.5-168

**Comment by alexbegt** [comment]
Please reopen a new ticket if this still occurs.
