### ISSUE TITLE
Conflicting recipes

### ISSUE THREAD

**Issue by IchigoGames** [progwml6/ironchest#198]
## Version Information
`Minecraft:1.14
`Forge: 28.0.93-any
`Iron Chests:ironchest-1.14.4-9.0.4

## Report Information
with ironchest and Cyclic-1.14.4-0.0.10 when you try to make temp tempered glass you cant make it it makes crystal chest upgrade

## Steps to Reproduce
add Chests:ironchest-1.14.4-9.0.4 add Cyclic-1.14.4-0.0.10 get in game try to craft cylic tempered glass.
![2019-09-07_00 07 53](https://user-images.githubusercontent.com/11888162/64470184-c6639480-d104-11e9-8faf-2ae08095cb69.png)

before you say report to other guy im reporting it to both of you if i had a craft tweaker or config options i just use that go get around this. but nothing out for 1.14

**Comment by progwml6** [comment]
Are you requesting an alternate recipe or a config to disable the crystal chest upgrade recipe?

**Comment by IchigoGames** [comment]
nvm the cylic dev said he would change the location of the obsidian in his mod so this would not conflict.
