### ISSUE TITLE
Upgrading I Like Wood Mod Chests Deletes Items

### ISSUE THREAD

**Issue by WenXin20** [progwml6/ironchest#200]
## Version Information
`Minecraft: v1.14.4`
`Forge: v28.1.22`
`Iron Chests: v9.1.5`
`I Like Wood: v1.1.2.3`
[Mod Link](https://www.curseforge.com/minecraft/mc-mods/i-like-wood)

## Report Information

- Upgrading chests from the I Like Wood Mod will delete any items currently in the chest.
- Chests also lose its current rotation upon upgrading.

## Steps to Reproduce

1. Craft a spruce or any other chest
2. Fill it with items.
2. Upgrade it to an iron chest.
3. Experience item loss and current chest rotation reset

## Forge Log

Nothing printed in the logs upon upgrading.

**Comment by Tfarcenim** [comment]
Now they don't work at all, isn't it possible to both upgrade and keep the contents/facing
