### ISSUE TITLE
Visual glitch with crystal chests

### ISSUE THREAD

**Issue by ErrorSys** [progwml6/ironchest#214]
## Version Information
`Minecraft: `1.12.2
`Forge: `14.23.5.2847
`Iron Chests: `1.12.2-7.0.72.847

## Report Information

Rendering Issue with diamond and crystal chests, they're both crystal chests (See images below). I'm not exactly sure what could be causing this, but it persists through game restarts and computer restarts.

## Steps to Reproduce

I don't believe that redoing what I did will produce the bug, but it here's how it happened: I was needing to relocate the chests elsewhere and broke them without emptying them of various items (other modded items included). When in my inventory, the chest appears clear, however, when placed down, they appear to be diamond chests (The Items can be seen clipping through the sides as they do their floating animation). When I look at the right chest, they both turn clear, but if I look at the left one or anywhere else, they turn back to diamond.

![2020-03-24_22 02 12](https://user-images.githubusercontent.com/38744863/77501085-8522a000-6e1c-11ea-8db2-ade1d39ac1b0.png)
![2020-03-24_22 02 16](https://user-images.githubusercontent.com/38744863/77501087-8653cd00-6e1c-11ea-85d4-88eb39cbc319.png)

There were no crashes in this bug

edit: added forge version

**Comment by ErrorSys** [comment]
It seems to have fixed itself now, still not sure why it happened

**Comment by alexbegt** [comment]
Are you able to provide a full list of mods that you have installed, and a copy of the world? It might be easier for me to duplicate this issue with your world since sometimes I am unable to recreate them.

**Comment by ErrorSys** [comment]
> Are you able to provide a full list of mods that you have installed, and a copy of the world? It might be easier for me to duplicate this issue with your world since sometimes I am unable to recreate them.

World: [Survival.zip (Google Drive Link)](https://drive.google.com/file/d/1lbKRwTbcAfJt4D5FEys1xe9KdCRkC_B3/view?usp=sharing)

Mod List:
![Mod List](https://user-images.githubusercontent.com/38744863/77721597-f2673a00-6fb0-11ea-86ad-ef596e12e6f5.PNG)

**Comment by ErrorSys** [comment]
If it helps, here's a video of what happens:
https://www.youtube.com/ZdU_BKr7kyI

**Comment by ErrorSys** [comment]
As it turns out, and I wish I had noticed before, but the issue seems to be caused by being on the border of a chunk and traversing between either chunk the chest is on. I placed the chest a few blocks from the border of said chunk and the issue disappeared. This is most likely due to Optifine or Minecraft's rendering engine.
