### ISSUE TITLE
Recipes error when server is starting

### ISSUE THREAD

**Issue by Oltrox** [progwml6/ironchest#217]
## Version Information
`Minecraft: 1.15.2`
`Forge: 31.1.41`
`Iron Chests: 10.0.3`

## Report Information

When starting a server, loads some recipies but not all of them. When you try to connect, it gives failed syncronization.

## Steps to Reproduce

Only install forge server, put the iron chest mod. Install the mod on the client. Start the server, and see the logs.

## Crash Log

https://pastebin.com/aCYSLT5y

## Forge Log

Not a client problem

**Comment by alexbegt** [comment]
So the recipes cannot load due to missing forge tags, those can be ignored since they do not matter, but it looks like you are missing a mod on the client, since you get different register numbers then what the server has.

**Comment by Oltrox** [comment]
Thx for the reply. I don't know why it works now... Sorry for the inconvenience 👍
