### ISSUE TITLE
Silver and copper bug

### ISSUE THREAD

**Issue by YourMotherr** [progwml6/ironchest#246]
## Version Information
`Minecraft: `1.15.2
`Forge: `32.2.49
`Iron Chests: `10.0.1

## Report Information

I can't find silver or copper ore at all and i cant find them in creative either and i can't craft silver or copper chests, when i try to use a mod for recipes it shows a barrier block and says "Empty tag: forge:ingots/silver
## Forge Log

https://gist.github.com/YourMotherr/2688ab734d88aa93cde72764c783f3de

**Comment by alexbegt** [comment]
We do not add copper or silver ore, you will have to add another mod that adds these ores to obtain the silver and copper chests.
