### ISSUE TITLE
Crystal chests not showing items inside

### ISSUE THREAD

**Issue by mikaela01a** [progwml6/ironchest#249]
## Version Information
`Minecraft:  1.16.5`
`Forge: 36.1.0`
`Iron Chests: 11.2.10`

## Report Information
Crystal chests do not show the items inside of them. No video setting seems to fix this. I am only putting non modded items into the chest. Logging out and back in is not working either

## Crash Log
NONE

## Forge Log
https://gist.github.com/mikaela01a/23fa4d3652352b7965d8d3a7f95b1455.js

Not sure if this is the right file

**Comment by prodigyrick** [comment]
> ## Version Information
> `Minecraft: 1.16.5`
> `Forge: 36.1.0`
> `Iron Chests: 11.2.10`
> 
> ## Report Information
> Crystal chests do not show the items inside of them. No video setting seems to fix this. I am only putting non modded items into the chest. Logging out and back in is not working either
> 
> ## Crash Log
> NONE
> 
> ## Forge Log
> https://gist.github.com/mikaela01a/23fa4d3652352b7965d8d3a7f95b1455.js
> 
> Not sure if this is the right file

same here.
