### ISSUE TITLE
ironchest-1.16.5-11.2.11.jar is not a valid mod file

### ISSUE THREAD

**Issue by SephirothWS** [progwml6/ironchest#250]
## Version Information
`Minecraft: ` 1.16.5
`Forge: ` 36.1.65
`Iron Chests: ` 11.2.11

## Report Information

Minecraft won't load with 11.2.11 - Forge reports the jarfile is not a valid mod file.

## Steps to Reproduce

Install Forge on Minecraft 1.16.5
Install Iron Chests 11.2.11
Launch
???
Profit

## Crash Log

N/A

## Forge Log

N/A

**Comment by alexbegt** [comment]
Thanks for the issue, I had tested it on my end end and it had worked fine, I have pulled the build down for now and will upload a new working one in the morning.

**Comment by alexbegt** [comment]
Please try ironchest-1.16.5-11.2.12 and let me know if it crashes.

**Comment by SephirothWS** [comment]
11.2.12 loads up fine. Thank you for the fix. :)
