### ISSUE TITLE
Ironchest-1.17.1-12.0.2 CTD on Forge 1.17.1 (37.0.12)

### ISSUE THREAD

**Issue by Baggytrousers27** [progwml6/ironchest#251]
Minecraft: 1.17.1
Forge: 37.0.12  
Iron Chests: 12.0.2

Just the mod, by itself causes forge 37.0.12 to crash.

1. Start MC 1.17.1 Forge 37.0.12 with ironchest-1.17.1-12.0.2 in mods folder
2. Game crashes

[Game output for crash](https://pastebin.com/SFh3Aci0)

**Comment by alexbegt** [comment]
It looks like you have a broken forge install, please try reinstalling Forge 37.0.13 and trying Iron Chests one more time.

**Comment by Baggytrousers27** [comment]
Well it's worked. How on earth did my forge break?
