### ISSUE TITLE
Invalid mod file for latest version

### ISSUE THREAD

**Issue by blackisme1** [progwml6/ironchest#261]
## Version Information
`Minecraft: 1.16.5`
`Forge: forge-36.2.19`
`Iron Chests: ironchest-1.16.5-11.2.20.jar`

## Report Information
Iron Chest will fail to load
Profile created in CurseForge client

## Steps to Reproduce
Launch the game with Iron Chests installed

## Forge Log
https://pastebin.com/jK091kvs

**Comment by alexbegt** [comment]
Please try the latest version that has been submitted to curseforge.

**Comment by blackisme1** [comment]
Fixed
