### ISSUE TITLE
Iron Chests has falied to load correctly

### ISSUE THREAD

**Issue by Dustynzzz** [progwml6/ironchest#286]
## Version Information
`Minecraft: 1.19
`Forge: 41.0.98
`Iron Chests: 14.0.2

**Comment by Dustynzzz** [comment]
I dont know why there's no crash log or forge log i'll upload it her
[crash-2022-07-16_14.49.17-fml.txt](https://github.com/progwml6/ironchest/files/9125786/crash-2022-07-16_14.49.17-fml.txt)
e

**Comment by Dustynzzz** [comment]
[latest.log](https://github.com/progwml6/ironchest/files/9125787/latest.log)

**Comment by MelanX** [comment]
Should be something from here: https://github.com/MinecraftForge/MinecraftForge/pull/8786 (guide linked in this PR)
Or here: https://github.com/MinecraftForge/MinecraftForge/pull/8840

**Comment by Dustynzzz** [comment]
Uhm
what am i suppose to do with that?

**Comment by MelanX** [comment]
Nothing, it's more for the dev as information how to resolve this issue.

**Comment by MelanX** [comment]
Oh, and you have "Iron Furnaces" in title, not "Iron Chests" :)

**Comment by Dustynzzz** [comment]
oh ok than thx

**Comment by SummerXXXX** [comment]
I have the same problem when start the game:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/10771754/181156838-20837e18-f427-4d2d-b3f5-2555c7fe9412.png">

Forge version: 41.1.0     ironchest-1.19-14.0.2
[crash-2022-07-27_11.44.35-fml.txt](https://github.com/progwml6/ironchest/files/9194889/crash-2022-07-27_11.44.35-fml.txt)

**Comment by Dot0exe** [comment]
i have the same issue for a long time 2 or 3 week maybe i dont know. i tried every thing that i can.

**Comment by MelanX** [comment]
There were breaking changes in 41.0.64 and 41.0.98 (iirc). You can’t do anything. You can just wait for the fix or create a pull request.

**Comment by wildkurt** [comment]
[crash-2022-08-07_19.53.30-fml.txt](https://github.com/progwml6/ironchest/files/9277920/crash-2022-08-07_19.53.30-fml.txt)
I keep getting the Iron Chests failed to load properly.
Minecraft: 1.19
Forge: 41.1.0

**Comment by MelanX** [comment]
Update the mod, it’s already fixed.

**Comment by Dot0exe** [comment]
tank you
