### ISSUE TITLE
[CRASHING] Fix for 14.3.2 @ 1.19.4

### ISSUE THREAD

**Issue by GamebP** [progwml6/ironchest#304]
## Version Information
`Minecraft: ` 1.19.4
`Forge: ` 1.19.4-45.1.0
`Iron Chests: ` ironchest-1.19.4-14.3.2.jar

## Report Information

![2023-06-28_17 20 39](https://github.com/progwml6/ironchest/assets/88152063/0ba60b73-864a-45a3-854e-b7ab3821ddaf)

## Steps to Reproduce

Have all other mods in the server,
Put the dirt chest down, then get kicked.

## Forge Log

[crash-2023-06-28_17.22.10-server.txt](https://github.com/progwml6/ironchest/files/11895792/crash-2023-06-28_17.22.10-server.txt)
[latest.log](https://github.com/progwml6/ironchest/files/11895806/latest.log)
![2023-06-28_17 20 39](https://github.com/progwml6/ironchest/assets/88152063/b5d91e16-ea3f-4e04-a0d5-d2ab3894a127)

**Comment by alexbegt** [comment]
Hi there, 

thank you for the bug report. I will look into it and fix it as soon as I can. 

Thank you.

**Comment by GamebP** [comment]
thanks, my friend said somenthing mean about this mod, but i would like this mod gets a little fix, beacuse of the issue we are having.

**Comment by armaDio** [comment]
Same thing happens in 1.20.1 version 14.4.3, after placing it down it will stay there transparent and crash the server as soon as you interact with it
When in single player it works as expected

**Comment by alexbegt** [comment]
Hi @GamebP Please update to [ironchest-1.19.4-14.3.4.jar](https://legacy.curseforge.com/minecraft/mc-mods/iron-chests/files/4614846) as this will fix the crash.

Hi @armaDio Please update to [ironchest-1.20.1-14.4.4.jar](https://legacy.curseforge.com/minecraft/mc-mods/iron-chests/files/4614852) as this will fix the crash.

**Comment by GamebP** [comment]
i can do it tommorow. its kinda late thanks for help

**Comment by GamebP** [comment]
It works on server.
