### ISSUE TITLE
Incorrect culling of chests (NeoForge BE Culling)

### ISSUE THREAD

**Issue by Lolothepro** [progwml6/ironchest#314]
## Version Information
`Minecraft: 1.21 `
`NeoForge: 21.0.30-beta ` 
`Iron Chests: 1.21-neoforge-16.0.6 `

## Steps to Reproduce
Place a chest from the mod 
Place a normal chest 
use `/neoforge debug_blockentity_renderbounds true`
compare

![2024-06-24_14 41 53](https://github.com/progwml6/ironchest/assets/68275908/e39c21fa-e618-4cf5-a310-cf28929c546f)

**Comment by alexbegt** [comment]
Hello, 

Iron Chests 16.0.7 should resolve this issue. If it does not, please do not hesitate to reopen this issue request.

Thank you!
