### ISSUE TITLE
Chests from this mod are not accessible to AE2

### ISSUE THREAD

**Issue by MuteTiefling** [progwml6/ironchest#315]
## Version Information
`Minecraft: 1.21`
`NeoForge: 21.0.42`
`Iron Chests: 16.0.6`

## Report Information

Chests from this mod are not accessible to AE2

## Steps to Reproduce

Connect Chests to AE2 via Storage Bus
Place items in the chest manually
Attempt to access items via Terminal. They do not appear

AE2 has no trouble reading other modded inventories I've tried.

## Crash Log

No Crash

**Comment by alexbegt** [comment]
Hello, 

Iron Chests 16.0.7 should resolve this issue. If it does not, please do not hesitate to reopen this issue request.

Thank you!
