### ISSUE TITLE
(1.8) Crash When Starting Server

### ISSUE THREAD

**Issue by Morpheus1101** [progwml6/ironchest#35]
When starting Server with NEI1.0.5.82  & Morpheus2.0.35 It crashes with following Crash Report:

http://www.mediafire.com/view/3grd171zs2vc6t6/UES2.txt

**Comment by RebaLynn1960** [comment]
FORGE VERSION
forge-1.8-11.14.0.1287-1.8-universal
MODS
CodeChickenCore-1.8
Fast-Leave-Decay-Mod-1.8
InventoryTweaks-1.59-dev-160
MrCrayfishFurnitureModv3.4.7-build5(1.8)
Not-Enough-Items-1.8

I get the same error as the person above.

**Comment by 61352151511** [comment]
Fixed with build 747

**Comment by RebaLynn1960** [comment]
I can confirm this is now working.
