### ISSUE TITLE
Client crashes when opening Crystal Chest on 1.8 Server

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [progwml6/ironchest#41]
When opening a Crystal Chest on my server, i get a [Netty Client IO #7/Error]: There was a critical exception handling a packet on channel IronChestio. This can affect just person at a time, or multiple, and it tends to disconnect people multiple times. Let me know if there is anything i can do to fix this

**Comment by progwml6** [comment]
need the entire log

**Comment by MajorGeneralRelativity** [comment]
Can you tell me how to obtain this log please? Do i dig around in the server logs, or is it somewhere else?

**Comment by 61352151511** [comment]
In the server files it would be in the logs folder called fml-server-latest.log, same with client except fml-client-latest.log not sure which one it would be in, a copy of both probably wouldn't hurt


Sent from Samsung MobileMajorGeneralRelativity <notifications@github.com> wrote:
Can you tell me how to obtain this log please? Do i dig around in the server logs, or is it somewhere else?

---

**Comment by MajorGeneralRelativity** [comment]
I'm busy today, but tomorrow I will get the client and server logs

**Comment by MajorGeneralRelativity** [comment]
In the client log, there was pages of registry information which I omitted from this log, but if you want it, I can put it in. You can find all the log below that here: http://pastebin.com/p6Wmsi8T

As for the server log, I can't even begin to comprehend it, so i dumped it all in at http://pastebin.com/pbak51u5

Both are from fml-client-latest.log or fml-server-latest.log. On the server, I also have Random Things 3.1 running, along with Iron Chests and the client also has NEI and WAILA running, but not all clients disconnected from the server from errors have NEI and WAILA. Let me know if you need any more info, or if there is anything I should do

**Comment by MajorGeneralRelativity** [comment]
P.S. sorry for the late response

**Comment by 61352151511** [comment]
Ok this is something to do with the packet's sending, server log gets cut off but I can see the issue in the client log. Not sure what's wrong with the packets

**Comment by MajorGeneralRelativity** [comment]
Is there anything I can do to help?
