### ISSUE TITLE
Crash Upon Startup

### ISSUE THREAD

**Issue by randysdoom** [progwml6/ironchest#43]
http://pastebin.com/wEVViEEG

Using Latest Ironchest for 1.7.10
Using Forge 1.7.10-10.13.3.1399-1.7.10-universal

**Comment by randysdoom** [comment]
Actually was not using latest version... 
Updated to latest version ironchest-1.7.10-6.0.62.742-universal
Crash Still Occurred

**Comment by TheJulianJES** [comment]
Are you using the righ forge version?

**Comment by The-Fireplace** [comment]
It looks to me like a mislabeled file, the error was caused by java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/network/IGuiHandler
in 1.7.10, that class is located at cpw/mods/fml/common/network/IGuiHandler
