### ISSUE TITLE
[6.0.107.754] Wrong chest orientation on upgrade

### ISSUE THREAD

**Issue by philobyte** [progwml6/ironchest#51]
When upgrading, the upgraded chest will never face the same direction as the original chest.

I seem to remember from earlier versions that you could fix this with a wrench (?), however, none of the mods that provide wrenches or omnitools are available for MC 1.8, which leaves the player with the tedious task of having to destroy and manually refill practically all upgraded chests.

**Comment by GirafiStudios** [comment]
Can confirm that this is still an issue in the latest 1.8.9 version (6.0.121.768).

**Comment by Hund** [comment]
Why is this issue ignored?

**Comment by 61352151511** [comment]
Chances are it's fixed in 1.9 although I haven't tested myself.
