### ISSUE TITLE
IronChest incompatibility

### ISSUE THREAD

**Issue by Mickimoo2** [progwml6/ironchest#53]
Is present in first beta, and is also present in 1017 beta.

http://pastie.org/private/xvb7vmzuhucbpxenbkpzq
http://pastie.org/private/pjtufde1cj6s4efuoaw1a

**Comment by cpw** [comment]
It's a sponge bug. IronChest is registering multiple TE names (old ones, for backwards compatibility).

**Comment by Mickimoo2** [comment]
progwml6 just told me to put it here so it reminds him to fix it when he wakes up.

**Comment by simon816** [comment]
`clazz` is null
```java
WOOD(0, 0, false, "", "", -1, Arrays.asList("plankWood"), null);
```
https://github.com/progwml6/ironchest/blob/master/src/main/java/cpw/mods/ironchest/IronChestType.java#L37

**Comment by gabizou** [comment]
@cpw The question is why IronChest is trying to register a `null` `Class<? extends TileEntity>` here, because that's what Sponge is capturing and failing (for obvious reasons). So please, clarify for me here where Sponge is breaking contract?

**Comment by Mickimoo2** [comment]
@cpw could you please enlighten this problem as I still need this fixed...

**Comment by gabizou** [comment]
@Mickimoo2 this can be closed now, the latest SpongeForge will appropriately handle cases like these.

**Comment by Mickimoo2** [comment]
Okay, thank you gabizou.
