### ISSUE TITLE
[1.9] Chests missing breaking particles

### ISSUE THREAD

**Issue by HanFox** [progwml6/ironchest#61]
I know it's not been out long and quite possibly this has just been overlooked, but chests have no texture for their particles when broken.

v6.0.126.771 on Forge 1782.

**Comment by alexbegt** [comment]
It wasn't overlooked, I just never got around to fixing them yet.

**Comment by Drullkus** [comment]
Pull Request #62 is here to save the day

**Comment by alexbegt** [comment]
Will be actually fixed after I get @progwml6 to look at it.

**Comment by alexbegt** [comment]
@HanFox Please download the new build, 6.0.129.773 when it becomes available on curse for fixed particles.
