### ISSUE TITLE
[1.9] 6.0.130.774 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [progwml6/ironchest#64]
Issue: iron-chests-2-1.9-6.0.130.774 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/4a278211d0ab54aa8875

fml server latest:
https://gist.github.com/6be2fad18a49dc88f21a

**Comment by kreezxil** [comment]
I rolled back to build 772 but it crashes 1.9 build 1811 too


Issue: IronChest{6.0.128.772} crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/5cb626ba31dfe7529e36

fml server latest:
https://gist.github.com/5b2ba905e14125674276

**Comment by alexbegt** [comment]
Should be fixed in build 775 (6.0.130.775) and in commit 0aae1ff
