### ISSUE TITLE
1.7.10 client crash when looking at a DirtChest 9000! (or five of them)

### ISSUE THREAD

**Issue by DDzwiedziu** [progwml6/ironchest#66]
Looking at a ~~diamond-level~~ chest. Started suddenly after teleporting with the RFTools Matter Transmitter/Receiver.

Pack: The Ferret Business 0.1.3
Forge 10.13.4.1566

Latest OptiFine: http://pastebin.com/hfTxDZ0u
No OptiFine: http://pastebin.com/BS3Z7JHi

EDIT: ~~not an diamond chest only.~~ Before I've teleported from that location I've placed five Dirtchests 9000!

EDIT 2: definitely the DirtChest 9000! was the problem. Removing them with MCEdit allowed me to start up the world.

**Comment by progwml6** [comment]
1.7.10 is no longer supported
