### ISSUE TITLE
[1.9.4] Rendering crash

### ISSUE THREAD

**Issue by MrTubzy456** [progwml6/ironchest#70]
I tped home using a command from Wuest utilities. When it tried rendering the chests I crashed to desktop. Here's the report: http://pastebin.com/CSEayrZH

I did a search for the same issue and came up with nothing, that doesn't mean there isn't one though. Anyways if you need anything else from me just let me know.

**Comment by alexbegt** [comment]
Fixed in: efd5046 (6.0.145.787)

**Comment by alexbegt** [comment]
Fixed in: efd5046 (6.0.145.787)
