### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by ConnorRowe** [progwml6/ironchest#73]
Version: 1.9.4-6.0.144.786

Whenever I die, my game crashes. I've only tested this with fall damage though. In the crash report it talks about something to do with rendering an iron chest but I'm not entirely sure.

[Crash report.](http://pastebin.com/H3z8aXq6)

**Comment by alexbegt** [comment]
How far are you from the IronChest when you die?

**Comment by alexbegt** [comment]
Also, Can I have your full log from when you crashed?

**Comment by ConnorRowe** [comment]
Hi, I think this is the correct log. 
[2016-06-13-6.log.gz](https://github.com/progwml6/ironchest/files/312834/2016-06-13-6.log.gz)

Although I think this issue may be caused by optifine because it occurs with my friend and I who both have it installed, but it doesn't occur with my other friend who does not have it installed. When I die I am a few chunks away from any IronChest, but I think it is loaded.

**Comment by alexbegt** [comment]
@ConnorRowe, Please get the crash report and the log from them, and if you don't mind me asking you, can you upload the resource pack also?

**Comment by alexbegt** [comment]
Actually, If you can try the new build that will be built soon, to see if you crash, that would be great!

**Comment by ConnorRowe** [comment]
Okay will do but for the time being, here is one of their crash reports.
http://pastebin.com/PwR0QCv3

**Comment by ConnorRowe** [comment]
@alexbegt Is there an ETA for the new build?

**Comment by alexbegt** [comment]
@ConnorRowe 6.0.145.787 should be out now.

**Comment by ConnorRowe** [comment]
@alexbegt Yes that has fixed it completely! Thank you very much! :)

**Comment by alexbegt** [comment]
@ConnorRowe Can you try with a chest that isn't a ironchest?

**Comment by ConnorRowe** [comment]
Yep its all working fine.

**Comment by alexbegt** [comment]
Correct texture? or all look like Iron Chests

**Comment by ConnorRowe** [comment]
Yes they all are correct textures.

**Comment by alexbegt** [comment]
Alright Cool!

**Comment by alexbegt** [comment]
Fixed in: efd5046 (6.0.145.787)
