### ISSUE TITLE
item lose on upgrade 1.10.2

### ISSUE THREAD

**Issue by falizure** [progwml6/ironchest#77]
im just starting on 1.10.2 server today and was upgrading half a double chest into a iron chest, and unlike in the past instead of splitting the inventory instead it deleted all the items inside it, if it is important the double chest was made of dark oak from the quark mod, latest version.

**Comment by alexbegt** [comment]
Oh no, that is not good. I'll look into this bug right now.

**Comment by alexbegt** [comment]
It seems I am unable to recreate this bug, Do you mind giving me a list of the mods that you currently have installed?

**Comment by falizure** [comment]
well fortunately the server is only in testing so i can create the objects i lost again, and this was sort of the point to find any issues, anyway sorrry, the mods and their current versions are. (a long list)
AppleCore-mc1.10.2-1.3.5.jar
AppleShields-0.1.0.jar
bdlib-1.12.0.2-mc1.10.2.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BetterFps-1.3.2.jar
BloodMagic-1.9.4-2.0.2-49.jar
BuildingBricks-1.10-2.0.9.jar
Chameleon-1.9.4-2.1.5.jar
chiselsandbits-11.5.jar
CustomBackgrounds-MC1.9.4-1.1.jar
CustomMainMenu-MC1.9.4-2.0.1.jar
deepresonance-1.9.4-1.2.0beta35.jar
Durability Show-1.9.4-3.1.1.jar
ElecCore-1.9.4-3.1.1.jar
EnderBags-1.9.4-2.0.0.jar
EnderCore-1.10-0.4.0.35-beta.jar
EnderIO-1.10-3.0.0.60_beta.jar
enderthin-1.9.4-0.6.8.jar
EnderZoon-1.10-1.2.3.43.jar
expandableBackpacks1.1.3-1.10.2.jar
extrautils2-1.10-alpha-1.0.0.jar
ezstorage-2.0.4.jar
FastLeafDecay-v10.jar
forestry_1.10.2-5.1.10.192.jar
gendustry-1.6.4.7-mc1.10.2.jar
Gravestone Mod 1.5.0.jar
inventorysorter-1.10-0.10.0+42.jar
ironchest-1.10-0.0.9.jar
itlt.10-0.0.9.jar
jei_1.10.2-3.7.5.227.jar
journeymap-1.10.2-5.2.4-unlimited.jar
justbackpacks-mc1.9.4-1.0.2.jar
Mantle-1.10-0.10.3.jar
mcjtylib-1.10-1.9.5.jar
MineMenu-1.10.X-1.4.4.B9-universal.jar
Morpheus-1.10-3.1.6.jar
mysticalagriculture-1.0.3.jar
OilCraft-1.10.2-0.3.4.jar
OredictionaryConverter-1.9.0.jar
ProgressiveAutomation-1.10.201.6.48.jar
Quark-beta-40.jar
RandomThings-MC1.10-3.7.4.jar
Reliquary-1.10.2-1.3.2.419.jar
ResourceLoader-MC1.9.4-1.5.1.jar
rftools-1.10-5.02.jar
rftoolsdim-1.10-4.30beta45.jar
roots-0.107.jar
SolarFluxReborn-1.10.2_0.4b.jar
StorageDrawers-1.9.4-3.1.11.jar
TConstruct-1.10-2.3.3a.jar
Tinkers' Addons-1.9.4-1.0.2.jar
vending-1.9.4-1.3.4.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10-1.1.7.jar
Wawla-1.10-2.3.0.193.jar
Running minecraft forge 12.18.0.2008

however this is only the mods on my client, the server is administered by a friend of mine so i dont know if any of these mods are inactive, normally i would pass on any issues to them however they are busy today so i figured id file the report myself, also if its important the right half of the chest was on a vanilla crafting table, and that was the half i upgraded to iron. Under those conditions i was not able to replicate the issue on singleplayer, and unfortunately the server is currently down and the admin is away so i cant attempt it on the server for the time being, also if it was item related i don't recall what all i had in the chest so i couldn't say if that's the case what might have caused it. Ether way thanks for the fast reply.

**Comment by Dalarrus** [comment]
I've had a similar issue, not all of my items, but rather entire item stacks will disappear, or just the stack will reduce to a quantity of 1, had this occur with both iron->gold and gold->diamond, 

Forge Version 12.18.3.2511 on Client & Server, 

Server is locally hosted, mod list is as follows:

aarandomlensblocker-1.10.2_1.0
Actually Additions-1.10.2-r105
Advanced Machines-60.0.4
Advanced Solar Panels-4.0.4
Advanced Rocketry-1.10.2-1.2.5a
ae2stuff-0.6.0.9-mc1.10.2
AkashicTome-1.0-5
analyzeio-1.10.2-0.3.3.22
angelRingToBauble-1.10.2-0.2.4.19+d71eb9e
AppleCore-mc1.10.2-3.1.0
AppleSkin-mc1.10.2-1.0.9
appliedenergistics2-rv4-stable-1
ArchitectureCraft-1.7.3-mc1.10.2
armorplus-1.10.2-8.7.1.2
astralsorcery-1.4.5
AutoRegLib-1.0-2
BadWitherNoCookie-1.10.2-0.0.1-5418dde
Bagginses-1.10.2-3.0.4g
Baubles-1.10.2-1.3.13
bdlib-1.12.4.25-mc1.10.2
BedBugs-1.10.2-1.1.6
BetterAchievements-1.10.2-0.3.3.10
BetterBuildersWands-1.10.2-0.11.1.220+f8232fe
BetterFps-1.4.5-1.10
BiblioCraft[v2.2.5][MC1.10.2]
BloodArsenal-1.10.2-2.1.0-22
BloodMagic-1.10.2-2.1.11-80
Bookshelf-1.10.2-1.4.4.347
Botania r1.9-341
BrandonsCore-1.10.2-2.1.14.137-universal
Chameleon-1.10.2-2.3.0
ChickenChunks-1.10.2-2.2.0.52-universal
Chisel-MC1.10.2-0.1.1.39
chiselsandbits-12.16
cm2-1.10.2-2.0.1-b141
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.9.320-universal
CoFHCore-1.10.2-4.1.12.17-universal
CommonCapabilities-1.10.2-1.3.4
CompactSolars-1.10.2-5.0.12.336-universal
compatlayer-1.10-0.3.0
Computronics-1.10.2-1.6.5
Controlling-1.0.5
CookingForBlockheads_1.10.2-4.2.45
Correlated-2.0.0-alpha3
CraftingTweaks_1.10.2-6.1.16
CraftTweaker-1.10.2-3.0.26
crossroads-1.10.2-1.3.7
CTM-MC1.10.2-0.2.3.26
cyberware-1.9.4-1.10.2-beta-0.2.10
Cyclic-1.10.2-1.10.30
CyclopsCore-1.9.4-0.10.10
DarkUtilities-1.1.8.finalrc2
deepresonance-1.1x-1.4.9
DefaultOptions_1.10.2-6.1.5
Ding-1.10.2-1.0.1
dirt2path-1.6.1
Draconic-Evolution-1.10.2-2.1.8.273-universal
ElecCore-1.10.2-1.7.431
embers-0.104
EnderBags-1.9.4-2.0.0
EnderCore-1.10.2-0.4.1.66-beta
EnderIO-1.10.2-3.1.193
EnderStorage-1.10.2-2.2.1.106-universal
EndMetals_1.9-1.0.4
EngineersWorkshop-1.3.7-1.10.2
ExtraBitManipulation-1.10.2-2.5.1
ExtraRails-1.10.2-1.1.1
extrautils2-1.10.2-1.7.2
ExtremeReactors-1.10.2-0.4.5.45
FastLeafDecay-v11
flatcoloredblocks-mc1.10-v4.4
FoamFix-1.11.2-0.7.3-Anarchy
forestry_1.10.2-5.2.17.388
Forgelin-1.6.0
FTBLib-1.1x-3.6.5
FTBUtilities-1.1x-3.6.5
funky-locomotion-1.10.2-alpha-0.0.3
gendustry-1.6.5.32-mc1.10.2
generators-0.9.20.23-mc1.10.2
GiacomosFishingNet1.10.2-1.4.4
Grapple-Hooks-1.10.2-1.0.8
Gravitation Suite-3.0.1
Guide-API-1.10.2-2.0.3-46
Hwyla-1.8.17-B31_1.10.2
ImmersiveEngineering-0.10-61
immersivepetroleum-1.10.2-1.1.3
industrialcraft-2-2.6.252-ex110
IntegratedDynamics-1.10.2-0.7.14
IntegratedTunnels-1.10.2-1.2.6
InventoryTweaks-1.62-dev-66
IronBackpacks-1.10.2-2.2.33
ironchest-1.10.2-7.0.15.804
itemscroller-1.10.2-0.11.0
jei_1.10.2-3.14.7.420
jeibees-0.9.0.5-mc1.10.2
journeymap-1.10.2-5.5.2
JustEnoughCalculation-1.10.2-2.6.5
JustEnoughResources-1.10.2-0.5.9.3
KleeSlabs_1.10.2-3.3.5
LibVulpes-1.10.2-0.2.6-universal
Mantle-1.10.2-1.1.5
mcjtylib-1.1x-2.5.1
MCMultiPart-1.4.0-universal
Mekanism-1.10.2-9.2.4.103
MekanismGenerators-1.10.2-9.2.4.103
MekanismTools-1.10.2-9.2.4.103
MFFS-1.10.2-3.0.1.0_1.10_d9fd06a
MineFactoryReloaded-[1.10.2]2.9.0B1-230
MineMenu-1.10.2-1.4.5-universal
MmmMmmMmmMmm-1.10.2-1.13
moartinkers-0.4.1
mobtotems-1.10.2-0.1.2
ModTweaker2-2.0.13
ModularPowersuits-1.10.2-1.2.129
morebees-1.10.2-1.4.1.1
moredefaultoptions-1.10.2-0.0.2
moreoverlays-1.11-mc1.10.2
Morpheus-1.10.2-3.1.13
Morph-o-Tool-1.0-12
mpbasic-1.10.2-1.1.5
mputils-1.10.2-1.2.9
MTLib-1.0.3
mysticalagriculture-1.10.2-1.5.9
natura-1.10.2-4.1.0.82
NetherMetals-1.10.2-1.1.4
NetherPortalFix_1.10.2-3.3.7
NoMobSpawningOnTrees-1.2.0-mc1.10.2
NoMoreRecipeConflict-0.6(1.10.2)
NotEnoughIDs-1.5.3.1
notenoughwands-1.1x-1.5.5
NuclearCraft-2.7a--1.10.2
OpenComputers-MC1.10.2-1.7.1.150
OreDictionaryConverter-1.9.1
OreExcavation-1.2.107
OreSpawn-1.10.2-3.2.1.100
p455w0rdslib-1.10.2-1.0.30
Pam's HarvestCraft 1.10.2j
pamscookables-1.10.2_1.0.0
platforms-1.10.0-1.2.10
PracticalLogistics2-1.10.2-2.0.2
pressure-1.3.1.27-mc1.10.2
ProgressiveAutomation-1.10.2-1.7.4
PSIonicUpgrades-r1.15
Psi-r1.0-42
Quark-r1.1-70
Railcraft_1.10.2-10.3.1
RandomThings-MC1.10.2-3.7.7.1
rangedpumps-0.3
ReAuth-3.5.2
RebornCore-1.10.2-2.13.6.142-universal
RebornStorage-1.10.2-1.0.3.30
RedstoneArsenal-1.10.2-2.1.3.8-universal
refinedstorage-1.2.26
Reliquary-1.10.2-1.3.3.664
ResourceLoader-MC1.9.4-1.5.1
rftools-1.1x-7.16
rftoolsctrl-1.1x-1.7.0
rftoolsdim-1.1x-5.05
roots-0.208
RouterReborn-1.10.2-4.0.1.98_universal
RouterRebornLib-1.10.2-0.0.2.115
Scannable-MC1.10.2-1.6.2.29
ShadowMC-1.10.2-3.6.1
shetiphiancore-1.10.0-3.3.11
Signals-1.10.2-0.5.1-universal
simpleretrogen-1.10-4.0.1+8
SimplyJetpacks2-1.10.2-2.1.3.55
SleepingBag-1.10.2-1.4.0
SonarCore-1.10.2-3.3.0
SoulShards-TOW-1.10.2-2.6.7-48
StevesCarts-1.10.2-2.2.0.86
StorageDrawers-1.10.2-3.7.10
Substratum-1.10.2-1.8.2.1
SuperCircuitMaker-1.0.4
taiga-1.10.2-1.2.6
TConstruct-1.10.2-2.6.5
TechReborn-1.10.2-2.1.18.235-universal
Tesla-1.10.2-1.2.1.50
teslafied-1.10.2-1.1.0
Thaumcraft-1.10.2-6.0.BETA2
thedragonlib-1.10.2-1.0.3.1
theoneprobe-1.1x-1.4.19
ThermalDynamics-1.10.2-2.0.11.19-universal
ThermalExpansion-1.10.2-5.1.10.28-universal
ThermalFoundation-1.10.2-2.1.5.12-universal
ThermalSmeltery-2.0.2
tinker_io-1.10.2-release 2.4.4b
Tinkers' Addons-1.10.2-1.0.6
TinkerToolLeveling-1.10.2-1.0.1
TombManyGraves-1.10.2-2.1.16
ToolBelt-1.10.2-1.7.1
topaddons-1.10.2-0.15.0
Translocators-1.10.2-2.1.4.55-universal
UniDict-1.10.2-2.9b
valkyrielib-1.10.2-0.10.6
vitality-2.4
WanionLib-1.10.2-1.3
WaterStrainer-1.9.4-1.4.2
WirelessCraftingGrid-1.10.2-1.0.0
WirelessCraftingTerminal-1.10.2-2.1.41
woot-1.10.2-1.4.1
xnet-1.5.0
Xtones-1.10.2-1.0.1-3
zerocore-1.10.2-0.1.1.1

[Server Config+scripts+startBat.zip](https://github.com/progwml6/ironchest/files/1669976/Server.Config.scripts.startBat.zip)

Attached is the configs, scripts file and the bat that is being used to start the server, it's not mine, it came with the pack, it's a modified All the mods V4 pack.

The issue occured, I noticed at first with Ae2 Quartz Crystals, both times, and Thaumcraft Crystals the 2nd time, as well as Tiberium crystals, not to say it only happens with crystals, just that those are the ones I've noticed it primarily with.

It occurred in a chunk claimed and loaded by a FTB team that is just me, it is not under spawn protection, and I am OPped on the server, it's locally hosted, connecting via 0.0.0.0, 16GB 3066 DDR4, Ryzen 5 1600 clocked at 3.7GHz,

Sorry about the semi-necro, but I'm playing on the same version, on a server, expereincing a very similar issue, if it needs to be it's own thread, I'll make a new one, just let me know.

If there's any more information you need, or anything else I could provide to help solve the issue, let me know :)

**Comment by alexbegt** [comment]
Hello,

If this bug still occurs, Please reopen a new ticket. I was never unable to recreate the bug.

Thanks,
Alexbegt
