### ISSUE TITLE
Crystal Chest Rendering As A Diamond Chest

### ISSUE THREAD

**Issue by JaRyCu** [progwml6/ironchest#82]
I'm playing a private modpack that is using Iron Chests.  We upgraded to v7.0.11.797 this morning, which I believe is the latest release, and my crystal chests are no longer crystal.  They still show in the tooltip as being a crystal chest, but a diamond chest image is rendered.  I can still see things coming through the sides, and I can see thing in the chest after I escape out of the interface, before the lid closes.

![2016-11-29_10 11 01](https://cloud.githubusercontent.com/assets/15949393/20718013/6c71f1d0-b625-11e6-9d0d-a06fd042d84a.png)

![2016-11-29_10 11 06](https://cloud.githubusercontent.com/assets/15949393/20718026/77a1d250-b625-11e6-8001-69366405f5f3.png)

**Comment by xSparky911x** [comment]
I too am having this problem except mine are showing as Iron Chest in the tooltip, and rendering as a Diamond Chest when I place a Crystal Chest. I am using Forge 2215 and Iron Chests 7.0.11.797

**Comment by alexbegt** [comment]
Hello,

If this bug still occurs, Please reopen a new ticket. I was never unable to recreate the bug in 2017.

Thanks,
Alexbegt
