### ISSUE TITLE
missing the required element 'version'

### ISSUE THREAD

**Issue by bhi-elliot** [progwml6/ironchest#83]
Good day,
Thank you for the wonderful mod. I am sure this isn't an important issue, but thought I would let you know what the server outputs regarding the mod when it loads, just as feedback.
## Versions
ironchest-1.11-7.0.17.799
spongeforge-1.11.2-2201-6.0.0-BETA-2012
forge-1.11.2-13.20.0.2201-universal
## Message
`[Server thread/WARN] [ironchest]: Mod ironchest is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.11-7.0.17.799`

**Comment by alexbegt** [comment]
This isn't a bug, IronChests creates the mod version in it's own way, hence how it's able to fallback to 1.11-7.0.17.799
