### ISSUE TITLE
Chest orientation

### ISSUE THREAD

**Issue by Daimanu06** [progwml6/ironchest#84]
Hello.

I just want to report a little issue in this mod.
When I load a map, occasionally, some chests do not face the good direction.
Supposing I place a chest facing south, it may later be loaded facing north, as shown in the screenshot.
When I quit the game and come back, the chests faces the good direction properly again.

The issue does not always occur. The building in the screenshot is split into 2 chunks, the border is in the middle.
As you can see it only occurs in the left chunk. The focused chest **(2)** and in the one close to the glowstone on the left **(1)** are supposed to face the same direction as the chest on the right **(3)**.

Mod version: 7.0.11 build 797
MC version: 1.10.2, but occurs in 1.8.9 as well
Other configuration: Java 1.8.0 x64, Forge 12.18, Optifine 1.10.2 (occurs without) and a few more mods.

Not important, but a little boring :)

Hope it helps!

![chest_issue](https://cloud.githubusercontent.com/assets/6599476/21944169/09c5621e-d9d5-11e6-9c0e-4224a60b3cc3.png)

**Comment by alexbegt** [comment]
Hello,

If this bug still occurs in 1.12.2, Please feel free to open a new ticket.

Thanks,
Alexbegt
