### ISSUE TITLE
Iron Shulker Boxes

### ISSUE THREAD

**Issue by TheDeviantCrafter** [progwml6/ironchest#86]
Shulker boxes offer some unique utility that chests don't. They keep their inventories, making them work as backpacks. They can be placed by dispensers and broken by pistons, making them useful in sorting systems and other redstone applications.
Unfortunately, by modded Minecraft standards, they're tiny. With that in mind, I recommend a mod that allows you to upgrade them into larger shulker boxes.

When this mod is ported to 1.11, I recommend adding upgraded versions of the shulker box. They can use the same recipes, and interact with the same upgrades. They would have the mechanics of a shulker box, but with an expanded inventory.

**Comment by alexbegt** [comment]
This feature is in the process of being added! Here's a little sneak peak: http://i.imgur.com/oc10ZSv.png

**Comment by Drullkus** [comment]
We're already ahead of you. Made these textures several weeks back ;)

**Comment by progwml6** [comment]
thanks for the textures @Drullkus

**Comment by progwml6** [comment]
Closing issue, as this will be out shortly
