### ISSUE TITLE
Crystal Chest buffer seems slow on insertion detection

### ISSUE THREAD

**Issue by sandalle** [progwml6/ironchest#87]
As found in https://github.com/raoulvdberge/refinedstorage/issues/1035 , Iron Chests (I was using a Crystal Chest) as a buffer seems to be slow on insertion detection (from what I was told). :)

![refined-storage 1035](https://cloud.githubusercontent.com/assets/2447608/23670657/510155a4-031d-11e7-82e4-0a6cb1e1ae8d.png)
[refined-storage.1035.nps.zip](https://github.com/progwml6/ironchest/files/825322/refined-storage.1035.nps.zip)

I have Ender IO item conduits with 15x speed upgrades (max) pulling from the Crystal Chest and Refined Storage Exporters and Crafters (each with 4x Speed upgrades (max)) outputting to the Crystal Chest.

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
Refined Storage: 1.2.22
Ender Core: 1.10.2-0.4.1.65-beta
Ender IO: 1.10.2-3.1.156
Iron Chest: 1.10.2-7.0.11.797

I hope that this helps. :)

**Comment by alexbegt** [comment]
If this is still a issue, please reopen a new ticket! Thanks!
