### ISSUE TITLE
[1.11.2] Crystal Chest Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [progwml6/ironchest#89]
On the 1.11.2 version of the mod whenever I interact (open by hand or use pipes) with a Crystal Chest after something's already in it I get this crash: https://media-elerium.cursecdn.com/attachments/202/531/crash-2017-04-18_19.txt

**Comment by alexbegt** [comment]
Are you running a mod pack, if you are, Can I have the name so I can test. Also, when you look at the Crystal Chest, does it show the items inside of it?

**Comment by EmosewaGamer** [comment]
The pack is Modern Skyblock and honestly I mostly payed attention to
recreating the crash that I didn't really notice if it shows up or not.

**Comment by VallenFrostweaver** [comment]
Similar problem. Stacks of any items cause a crash. Running Modded Mischief II modpack.
https://hastebin.com/iwisuwuqig.coffeescript

**Comment by savosdarkran** [comment]
Same issue here.  No items show in the chest when you look at it.  Custom modpack not publicly available.
[crash-2017-04-24_23.31.05-client.txt](https://github.com/progwml6/ironchest/files/953813/crash-2017-04-24_23.31.05-client.txt)

**Comment by kreezxil** [comment]
I see this is closed, I think my player's report is the same as the op crash report: https://pastebin.com/UKihGLAZ

I've asked my player what steps they have taken to cause the crash and I have not gotten a response. I've tried to duplicate it to no avail. I placed a stack in a crystal chest, it works fine. I put a hopper duct on it, works fine. Put a regular hopper too.

I'm the pack author for Sky Colony on CurseForge.

I'm hoping this closed issue means you'll have an update version of ironchests out soon, I am currently on build 800.

**Comment by VallenFrostweaver** [comment]
It wasn't 1 stack. It was several.

**Comment by EmosewaGamer** [comment]
It's miledly interesting how we're pack makers reportimg the crash, but I guess weirdly enough, not many people know how to read logs or directly send it to the mod's GitHub when they kow the cause of the crash. I have the most popular pack of the few though. 😊

**Comment by kreezxil** [comment]
@EmosewaGamer heh, please name your pack.

Anyhoo, I see that ironchest-1.11.2-7.0.18.800 just came out, are the issues from this thread addressed in it?

**Comment by EmosewaGamer** [comment]
The #1 skyblock pack for 1.11.2, Modern Skyblock. I really thought that you took some of my ideas, but I guess not. Honestly today I was thinking about adding MineColonies to my pack, but the more I thought about it the less of a need I had for it. Also there's no 1.11.2 version of the latest update so...

**Comment by kreezxil** [comment]
Ok, this is not the place to debate this. However, you and others like you
can rest assured that my ideas are my own. I don't look at another pack and
clone it and tweak it to try and usurp it or otherwise. I put together
packs in ways that I want and I hope that others will like them not feel
hurt by them.

**Comment by EmosewaGamer** [comment]
I never said you cloned it. Even if you did take some inspiration I wouldn't mind it as it would tell me that I did something good enough for others to use. And yeah, this is surely not the place for this.
