### ISSUE TITLE
1.11.2-7.0.0.18.800 Client Side Rending Crash ( Crystal Chest )

### ISSUE THREAD

**Issue by TwitchtvCarbs** [progwml6/ironchest#90]
Any items in the crystal chest that have 2 stacks ( 64 x 2 ) are not rendered in the block model that shows the contents of the chest.

THEN

When you have 2 different items with 2 stacks ( 64 x 2 ) each the client will crash producing this crash log here:
https://pastebin.com/JmbgNQvd

The crash happens as soon as you drop the second stack of the second item in the chest as seen below
https://gyazo.com/96e182586ce40137b1776a1a7f2d65e6

**Comment by alexbegt** [comment]
Fixed in the latest commit, Don't know why git didn't close this :P
