### ISSUE TITLE
Upgrading a Shulker box voids its inventory

### ISSUE THREAD

**Issue by Hund** [progwml6/ironchest#93]
I just updated to the new version (7.0.21.806) and when I upgrade a Shulker box (to any tier) the inventory gets voided.

**Comment by alexbegt** [comment]
Are you running Iron Chests on a server or in singleplayer? I am unable to recreate the inventory getting voided.

**Comment by Hund** [comment]
Server.

**Comment by alexbegt** [comment]
Are you running a mod pack? If so, is there any way for me to download it?

**Comment by Hund** [comment]
It's not a modpack, but here's the mods I have on the server:

```
Aroma1997Core-1.11.2-1.2.0.0.jar
AromaBackup-1.11-2.1.0.0.jar
Baubles-1.11-1.4.4.jar
BedBugs-1.11.2-1.1.7.jar
BetterBuildersWands-1.11-0.11.1.239+9162f74.jar
BetterFps-1.4.5.jar
Botania r1.9-343.jar
ChickenChunks-1.11.2-2.3.0.63-universal.jar
CodeChickenLib-1.11.2-2.7.0.268-universal.jar
CraftingCraft_1.11-5.1.1.jar
GraveStone Mod 1.7.2.jar
hammerz-1.11.2-0.1.4.27.jar
Harvest-1.12-1.2.1-13.jar
InventoryTweaks-1.62.jar
ironchest-1.11.2-7.0.21.806.jar
jei_1.11.2-4.3.5.277.jar
journeymap-1.11.2-5.4.6.jar
mod_list.json
Morpheus-1.11.2-3.2.14.jar
supercraftingframe-1.11-1.2.1.89.jar
torchmaster_1.11.2-1.3.3.37.jar
Waila-1.7.1_1.11.2.jar
Wawla-1.11.2-2.4.0.231.jar
```

**Comment by 61352151511** [comment]
I can't be of any help at the moment but just throwing it out there, that is a mod pack. If you're playing with multiple mods it is a pack of mods or "modpack"

**Comment by Hund** [comment]
That's true. :) Every mod is from Curseforge. So if you want to replicate it, you can download everything from there.

**Comment by alexbegt** [comment]
Are you crafting the next tier up or are you using the upgrades to upgrade it?

**Comment by alexbegt** [comment]
Also If you don't mind, Can you add me on curse to help me test? (Alexbegt is my curse), or if you prefer discord, my discord is alexbegt#9182 .

**Comment by Hund** [comment]
I crafted the next tier up. Didn't think of the upgraded. I just tested them and they work just fine. :)

**Comment by Hund** [comment]
I sent you a request on Discord.
