### ISSUE TITLE
[1.12] Latest Forge causes crash on Startup

### ISSUE THREAD

**Issue by SnowShock35** [progwml6/ironchest#98]
Hello, 

It appears there's an issue with Iron Chests and the latest Forge, here's the details....

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2339 (Latest as of the time of making this. Build 2340 wasn't far behind.. will test and update once it's available)
- Iron Chests 7.0.25.811

### Issue Information

Crash on startup caused by a cast exception. 

### Issue Media

https://pastebin.com/RGuABwhT

**Comment by Kris1432** [comment]
Getting the same issue over here. Using Forge 2340.

**Comment by SnowShock35** [comment]
@Kris1432 Thanks for confirming that for me 🙂

**Comment by Excederus** [comment]
Have the same issue on Forge versions: 2337, 2338, 2339, 2340

**Comment by Migmag789** [comment]
Can you make a 2342 compat version plz ?
