### ISSUE TITLE
[1.12] [Suggestion] Re-order Creative tab (... What a mess)

### ISSUE THREAD

**Issue by SnowShock35** [progwml6/ironchest#99]
Hello,

So in the latest 1.12 version of Iron Chests, the creative tab is quite... a mess to put it lightly. All the various boxes and upgrades are all in a what appears to be mostly random order. The mod's items/blocks display far better in JEI too so it's not a matter of it being the same in JEI too it's simply just the creative tab. I've linked a screenshot below of perhaps a better way of laying them out.

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1497954262-48b01106.png)

**Comment by alexbegt** [comment]
I have implemented your suggestion for 1.12!
